// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema.ext.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	cinema.ext.proto
	comment.ext.proto
	film.ext.proto
	order.ext.proto
	place.ext.proto
	user.ext.proto

It has these top-level messages:
	LocationCinemaReq
	LocationCinemaRsp
	Cinema
	GetCinemaMessageReq
	GetCinemaMessageRsp
	HotCommentReq
	HotCommentRsp
	CommentData
	CommentMini
	CommentPlus
	CommentRecord
	MakeCommentReq
	MakeCommentRsp
	HotPlayMoviesReq
	HotPlayMoviesRep
	Movie
	HotMovie
	FilmAllMessage
	MovieDetailReq
	MovieDetailRep
	Release
	MovieCreditsWithTypesReq
	MovieCreditsWithTypesRep
	Type
	Persons
	ImageAllReq
	ImageAllRep
	Image
	LocationMoviesReq
	LocationMoviesRep
	MovieComingNewReq
	MovieComingNewRep
	SearchRep
	SearchReq
	SearchMovie
	Genres
	Rating
	Images
	GetFilmsByCidReq
	GetFilmsByCidRsp
	WantTicketReq
	WantTicketRsp
	TicketReq
	TicketRsp
	Order
	LookOrdersReq
	LookOrdersRsp
	PayOrderReq
	PayOrderRsp
	UndoOrderReq
	UndoOrderRsp
	HotCitiesByCinemaReq
	HotCitiesByCinemaRep
	Place
	RegistAccountReq
	RegistAccountRsp
	LoginAccountReq
	LoginAccountRsp
	ResetAccountReq
	ResetAccountRsp
	WantScoreReq
	WantScoreRsp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LocationCinemaReq struct {
	LocationId int64 `protobuf:"varint,1,opt,name=locationId" json:"locationId,omitempty"`
}

func (m *LocationCinemaReq) Reset()                    { *m = LocationCinemaReq{} }
func (m *LocationCinemaReq) String() string            { return proto.CompactTextString(m) }
func (*LocationCinemaReq) ProtoMessage()               {}
func (*LocationCinemaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LocationCinemaReq) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

type LocationCinemaRsp struct {
	Cinemas []*Cinema `protobuf:"bytes,1,rep,name=cinemas" json:"cinemas,omitempty"`
}

func (m *LocationCinemaRsp) Reset()                    { *m = LocationCinemaRsp{} }
func (m *LocationCinemaRsp) String() string            { return proto.CompactTextString(m) }
func (*LocationCinemaRsp) ProtoMessage()               {}
func (*LocationCinemaRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LocationCinemaRsp) GetCinemas() []*Cinema {
	if m != nil {
		return m.Cinemas
	}
	return nil
}

type Cinema struct {
	CinemaId    int64  `protobuf:"varint,1,opt,name=cinemaId" json:"cinemaId,omitempty"`
	CinemaName  string `protobuf:"bytes,2,opt,name=cinemaName" json:"cinemaName,omitempty"`
	CinemaAdd   string `protobuf:"bytes,3,opt,name=cinemaAdd" json:"cinemaAdd,omitempty"`
	LocationId  int64  `protobuf:"varint,4,opt,name=locationId" json:"locationId,omitempty"`
	CinemaTypes string `protobuf:"bytes,5,opt,name=cinemaTypes" json:"cinemaTypes,omitempty"`
}

func (m *Cinema) Reset()                    { *m = Cinema{} }
func (m *Cinema) String() string            { return proto.CompactTextString(m) }
func (*Cinema) ProtoMessage()               {}
func (*Cinema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Cinema) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

func (m *Cinema) GetCinemaName() string {
	if m != nil {
		return m.CinemaName
	}
	return ""
}

func (m *Cinema) GetCinemaAdd() string {
	if m != nil {
		return m.CinemaAdd
	}
	return ""
}

func (m *Cinema) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *Cinema) GetCinemaTypes() string {
	if m != nil {
		return m.CinemaTypes
	}
	return ""
}

type GetCinemaMessageReq struct {
	MovieId    int64  `protobuf:"varint,1,opt,name=movieId" json:"movieId,omitempty"`
	LocationId int64  `protobuf:"varint,2,opt,name=locationId" json:"locationId,omitempty"`
	Day        string `protobuf:"bytes,3,opt,name=day" json:"day,omitempty"`
}

func (m *GetCinemaMessageReq) Reset()                    { *m = GetCinemaMessageReq{} }
func (m *GetCinemaMessageReq) String() string            { return proto.CompactTextString(m) }
func (*GetCinemaMessageReq) ProtoMessage()               {}
func (*GetCinemaMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetCinemaMessageReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *GetCinemaMessageReq) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *GetCinemaMessageReq) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

type GetCinemaMessageRsp struct {
	CinemaName     string `protobuf:"bytes,1,opt,name=cinemaName" json:"cinemaName,omitempty"`
	CinemaAddress  string `protobuf:"bytes,2,opt,name=cinemaAddress" json:"cinemaAddress,omitempty"`
	CinemaSupport  string `protobuf:"bytes,3,opt,name=cinemaSupport" json:"cinemaSupport,omitempty"`
	CinemaCard     int64  `protobuf:"varint,4,opt,name=cinemaCard" json:"cinemaCard,omitempty"`
	CinemaMinPrice int64  `protobuf:"varint,5,opt,name=cinemaMinPrice" json:"cinemaMinPrice,omitempty"`
	CinemaDiscount int64  `protobuf:"varint,6,opt,name=cinemaDiscount" json:"cinemaDiscount,omitempty"`
}

func (m *GetCinemaMessageRsp) Reset()                    { *m = GetCinemaMessageRsp{} }
func (m *GetCinemaMessageRsp) String() string            { return proto.CompactTextString(m) }
func (*GetCinemaMessageRsp) ProtoMessage()               {}
func (*GetCinemaMessageRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetCinemaMessageRsp) GetCinemaName() string {
	if m != nil {
		return m.CinemaName
	}
	return ""
}

func (m *GetCinemaMessageRsp) GetCinemaAddress() string {
	if m != nil {
		return m.CinemaAddress
	}
	return ""
}

func (m *GetCinemaMessageRsp) GetCinemaSupport() string {
	if m != nil {
		return m.CinemaSupport
	}
	return ""
}

func (m *GetCinemaMessageRsp) GetCinemaCard() int64 {
	if m != nil {
		return m.CinemaCard
	}
	return 0
}

func (m *GetCinemaMessageRsp) GetCinemaMinPrice() int64 {
	if m != nil {
		return m.CinemaMinPrice
	}
	return 0
}

func (m *GetCinemaMessageRsp) GetCinemaDiscount() int64 {
	if m != nil {
		return m.CinemaDiscount
	}
	return 0
}

func init() {
	proto.RegisterType((*LocationCinemaReq)(nil), "pb.LocationCinemaReq")
	proto.RegisterType((*LocationCinemaRsp)(nil), "pb.LocationCinemaRsp")
	proto.RegisterType((*Cinema)(nil), "pb.Cinema")
	proto.RegisterType((*GetCinemaMessageReq)(nil), "pb.GetCinemaMessageReq")
	proto.RegisterType((*GetCinemaMessageRsp)(nil), "pb.GetCinemaMessageRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CinemaServiceExt service

type CinemaServiceExtClient interface {
	// 地点影城
	LocationCinema(ctx context.Context, in *LocationCinemaReq, opts ...client.CallOption) (*LocationCinemaRsp, error)
}

type cinemaServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewCinemaServiceExtClient(serviceName string, c client.Client) CinemaServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &cinemaServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *cinemaServiceExtClient) LocationCinema(ctx context.Context, in *LocationCinemaReq, opts ...client.CallOption) (*LocationCinemaRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CinemaServiceExt.LocationCinema", in)
	out := new(LocationCinemaRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CinemaServiceExt service

type CinemaServiceExtHandler interface {
	// 地点影城
	LocationCinema(context.Context, *LocationCinemaReq, *LocationCinemaRsp) error
}

func RegisterCinemaServiceExtHandler(s server.Server, hdlr CinemaServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CinemaServiceExt{hdlr}, opts...))
}

type CinemaServiceExt struct {
	CinemaServiceExtHandler
}

func (h *CinemaServiceExt) LocationCinema(ctx context.Context, in *LocationCinemaReq, out *LocationCinemaRsp) error {
	return h.CinemaServiceExtHandler.LocationCinema(ctx, in, out)
}

func init() { proto.RegisterFile("cinema.ext.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xd1, 0x4a, 0xf3, 0x40,
	0x10, 0x85, 0xff, 0x6d, 0x7e, 0x5b, 0x3b, 0xc5, 0x52, 0x57, 0x84, 0xa5, 0x88, 0x84, 0x50, 0xa4,
	0x57, 0xb9, 0x68, 0xaf, 0xbc, 0x53, 0xaa, 0x88, 0x60, 0x45, 0xd2, 0xbe, 0xc0, 0x36, 0x19, 0x64,
	0xc1, 0x66, 0xd7, 0xec, 0xb6, 0xb4, 0xef, 0xe3, 0x0b, 0xfa, 0x06, 0x92, 0x6c, 0x9a, 0xa4, 0x49,
	0xef, 0x76, 0xbe, 0x99, 0xe5, 0x9c, 0x19, 0x0e, 0x0c, 0x42, 0x11, 0xe3, 0x9a, 0xfb, 0xb8, 0x33,
	0xbe, 0x4a, 0xa4, 0x91, 0xb4, 0xa5, 0x56, 0xde, 0x14, 0x2e, 0xdf, 0x64, 0xc8, 0x8d, 0x90, 0xf1,
	0x2c, 0xeb, 0x07, 0xf8, 0x4d, 0x6f, 0x01, 0xbe, 0x72, 0xf8, 0x1a, 0x31, 0xe2, 0x92, 0xb1, 0x13,
	0x54, 0x88, 0x77, 0xdf, 0xf8, 0xa4, 0x15, 0x1d, 0x41, 0xc7, 0x2a, 0x68, 0x46, 0x5c, 0x67, 0xdc,
	0x9b, 0x80, 0xaf, 0x56, 0x7e, 0xde, 0x3f, 0xb4, 0xbc, 0x1f, 0x02, 0x6d, 0xcb, 0xe8, 0x10, 0xce,
	0x2d, 0x2d, 0x34, 0x8a, 0x3a, 0x75, 0x60, 0xdf, 0xef, 0x7c, 0x8d, 0xac, 0xe5, 0x92, 0x71, 0x37,
	0xa8, 0x10, 0x7a, 0x03, 0x5d, 0x5b, 0x3d, 0x46, 0x11, 0x73, 0xb2, 0x76, 0x09, 0x6a, 0xfe, 0xff,
	0xd7, 0xfd, 0x53, 0x17, 0x7a, 0x76, 0x78, 0xb9, 0x57, 0xa8, 0xd9, 0x59, 0xf6, 0xbf, 0x8a, 0x3c,
	0x0e, 0x57, 0x2f, 0x68, 0xac, 0xd1, 0x39, 0x6a, 0xcd, 0x3f, 0x31, 0x3d, 0x0c, 0x83, 0xce, 0x5a,
	0x6e, 0x05, 0x16, 0x8e, 0x0f, 0x65, 0x4d, 0xb2, 0xd5, 0x90, 0x1c, 0x80, 0x13, 0xf1, 0x7d, 0x6e,
	0x35, 0x7d, 0x7a, 0xbf, 0xe4, 0x84, 0x86, 0x56, 0xb5, 0xd5, 0x49, 0x63, 0xf5, 0x11, 0x5c, 0x14,
	0x9b, 0x26, 0xa8, 0x75, 0x7e, 0x9d, 0x63, 0x58, 0x4e, 0x2d, 0x36, 0x4a, 0xc9, 0xc4, 0xe4, 0xca,
	0xc7, 0xb0, 0xd4, 0x9a, 0xf1, 0xa4, 0x38, 0x54, 0x49, 0xe8, 0x1d, 0xf4, 0x6d, 0x35, 0x17, 0xf1,
	0x47, 0x22, 0x42, 0xcc, 0x6e, 0xe5, 0x04, 0x35, 0x5a, 0xce, 0x3d, 0x09, 0x1d, 0xca, 0x4d, 0x6c,
	0x58, 0xbb, 0x3a, 0x77, 0xa0, 0x93, 0x25, 0x0c, 0xec, 0xbe, 0x0b, 0x4c, 0xb6, 0x22, 0xc4, 0xe7,
	0x9d, 0xa1, 0x0f, 0xd0, 0x3f, 0x0e, 0x13, 0xbd, 0x4e, 0x83, 0xd3, 0x48, 0xe5, 0xf0, 0x14, 0xd6,
	0xca, 0xfb, 0xb7, 0x6a, 0x67, 0x71, 0x9e, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xfe, 0xc1,
	0x41, 0xe2, 0x02, 0x00, 0x00,
}
