// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cms.ext.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserLoginReq struct {
	User     string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UserLoginReq) Reset()                    { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string            { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()               {}
func (*UserLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *UserLoginReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginRsp struct {
	AdminID    int64  `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
	CinemaName string `protobuf:"bytes,3,opt,name=cinemaName" json:"cinemaName,omitempty"`
}

func (m *UserLoginRsp) Reset()                    { *m = UserLoginRsp{} }
func (m *UserLoginRsp) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRsp) ProtoMessage()               {}
func (*UserLoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *UserLoginRsp) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

func (m *UserLoginRsp) GetCinemaName() string {
	if m != nil {
		return m.CinemaName
	}
	return ""
}

type UpdateMessageReq struct {
	Table string `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	Json  string `protobuf:"bytes,2,opt,name=json" json:"json,omitempty"`
	Num   string `protobuf:"bytes,3,opt,name=num" json:"num,omitempty"`
}

func (m *UpdateMessageReq) Reset()                    { *m = UpdateMessageReq{} }
func (m *UpdateMessageReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateMessageReq) ProtoMessage()               {}
func (*UpdateMessageReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *UpdateMessageReq) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *UpdateMessageReq) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func (m *UpdateMessageReq) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

type UpdateMessageRsp struct {
}

func (m *UpdateMessageRsp) Reset()                    { *m = UpdateMessageRsp{} }
func (m *UpdateMessageRsp) String() string            { return proto.CompactTextString(m) }
func (*UpdateMessageRsp) ProtoMessage()               {}
func (*UpdateMessageRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type AllFilmsReq struct {
	Page    int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	AdminID int64 `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *AllFilmsReq) Reset()                    { *m = AllFilmsReq{} }
func (m *AllFilmsReq) String() string            { return proto.CompactTextString(m) }
func (*AllFilmsReq) ProtoMessage()               {}
func (*AllFilmsReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *AllFilmsReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllFilmsReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type AllFilmsRsp struct {
	Total int64   `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Films []*Film `protobuf:"bytes,2,rep,name=films" json:"films,omitempty"`
}

func (m *AllFilmsRsp) Reset()                    { *m = AllFilmsRsp{} }
func (m *AllFilmsRsp) String() string            { return proto.CompactTextString(m) }
func (*AllFilmsRsp) ProtoMessage()               {}
func (*AllFilmsRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *AllFilmsRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *AllFilmsRsp) GetFilms() []*Film {
	if m != nil {
		return m.Films
	}
	return nil
}

type Film struct {
	MovieID              int64    `protobuf:"varint,1,opt,name=movieID" json:"movieID,omitempty"`
	Img                  string   `protobuf:"bytes,2,opt,name=img" json:"img,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	IsSelectSeat         int64    `protobuf:"varint,4,opt,name=isSelectSeat" json:"isSelectSeat,omitempty"`
	FilmPrice            float32  `protobuf:"fixed32,5,opt,name=filmPrice" json:"filmPrice,omitempty"`
	FilmScreenwriter     string   `protobuf:"bytes,6,opt,name=filmScreenwriter" json:"filmScreenwriter,omitempty"`
	FilmDirector         string   `protobuf:"bytes,7,opt,name=filmDirector" json:"filmDirector,omitempty"`
	CommentNum           int64    `protobuf:"varint,8,opt,name=commentNum" json:"commentNum,omitempty"`
	TitleCn              string   `protobuf:"bytes,9,opt,name=titleCn" json:"titleCn,omitempty"`
	TitleEn              string   `protobuf:"bytes,10,opt,name=titleEn" json:"titleEn,omitempty"`
	IsSupportInlineWatch int64    `protobuf:"varint,11,opt,name=isSupportInlineWatch" json:"isSupportInlineWatch,omitempty"`
	CreateAt             string   `protobuf:"bytes,12,opt,name=createAt" json:"createAt,omitempty"`
	Type                 string   `protobuf:"bytes,13,opt,name=type" json:"type,omitempty"`
	FilmDrama            string   `protobuf:"bytes,14,opt,name=filmDrama" json:"filmDrama,omitempty"`
	CommonSpecial        string   `protobuf:"bytes,15,opt,name=commonSpecial" json:"commonSpecial,omitempty"`
	UserAccessTimes      int64    `protobuf:"varint,16,opt,name=userAccessTimes" json:"userAccessTimes,omitempty"`
	FilmBoxoffice        float32  `protobuf:"fixed32,17,opt,name=filmBoxoffice" json:"filmBoxoffice,omitempty"`
	WantedCount          int64    `protobuf:"varint,18,opt,name=wantedCount" json:"wantedCount,omitempty"`
	UserCommentTimes     int64    `protobuf:"varint,19,opt,name=userCommentTimes" json:"userCommentTimes,omitempty"`
	CompanyIssued        string   `protobuf:"bytes,20,opt,name=companyIssued" json:"companyIssued,omitempty"`
	Country              string   `protobuf:"bytes,21,opt,name=country" json:"country,omitempty"`
	RatingFinal          float32  `protobuf:"fixed32,22,opt,name=ratingFinal" json:"ratingFinal,omitempty"`
	Is3D                 int64    `protobuf:"varint,23,opt,name=is3D" json:"is3D,omitempty"`
	IsDMAX               int64    `protobuf:"varint,24,opt,name=isDMAX" json:"isDMAX,omitempty"`
	IsFilter             int64    `protobuf:"varint,25,opt,name=isFilter" json:"isFilter,omitempty"`
	IsHot                int64    `protobuf:"varint,26,opt,name=isHot" json:"isHot,omitempty"`
	IsIMAX               int64    `protobuf:"varint,27,opt,name=isIMAX" json:"isIMAX,omitempty"`
	IsIMAX3D             int64    `protobuf:"varint,28,opt,name=isIMAX3D" json:"isIMAX3D,omitempty"`
	IsNew                int64    `protobuf:"varint,29,opt,name=isNew" json:"isNew,omitempty"`
	IsTicking            int64    `protobuf:"varint,30,opt,name=isTicking" json:"isTicking,omitempty"`
	RDay                 int64    `protobuf:"varint,31,opt,name=rDay" json:"rDay,omitempty"`
	RMonth               int64    `protobuf:"varint,32,opt,name=rMonth" json:"rMonth,omitempty"`
	RYear                int64    `protobuf:"varint,33,opt,name=rYear" json:"rYear,omitempty"`
	ActorNames           []string `protobuf:"bytes,34,rep,name=actorNames" json:"actorNames,omitempty"`
	RYMD                 string   `protobuf:"bytes,35,opt,name=rYMD" json:"rYMD,omitempty"`
}

func (m *Film) Reset()                    { *m = Film{} }
func (m *Film) String() string            { return proto.CompactTextString(m) }
func (*Film) ProtoMessage()               {}
func (*Film) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Film) GetMovieID() int64 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *Film) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *Film) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Film) GetIsSelectSeat() int64 {
	if m != nil {
		return m.IsSelectSeat
	}
	return 0
}

func (m *Film) GetFilmPrice() float32 {
	if m != nil {
		return m.FilmPrice
	}
	return 0
}

func (m *Film) GetFilmScreenwriter() string {
	if m != nil {
		return m.FilmScreenwriter
	}
	return ""
}

func (m *Film) GetFilmDirector() string {
	if m != nil {
		return m.FilmDirector
	}
	return ""
}

func (m *Film) GetCommentNum() int64 {
	if m != nil {
		return m.CommentNum
	}
	return 0
}

func (m *Film) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *Film) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *Film) GetIsSupportInlineWatch() int64 {
	if m != nil {
		return m.IsSupportInlineWatch
	}
	return 0
}

func (m *Film) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Film) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Film) GetFilmDrama() string {
	if m != nil {
		return m.FilmDrama
	}
	return ""
}

func (m *Film) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

func (m *Film) GetUserAccessTimes() int64 {
	if m != nil {
		return m.UserAccessTimes
	}
	return 0
}

func (m *Film) GetFilmBoxoffice() float32 {
	if m != nil {
		return m.FilmBoxoffice
	}
	return 0
}

func (m *Film) GetWantedCount() int64 {
	if m != nil {
		return m.WantedCount
	}
	return 0
}

func (m *Film) GetUserCommentTimes() int64 {
	if m != nil {
		return m.UserCommentTimes
	}
	return 0
}

func (m *Film) GetCompanyIssued() string {
	if m != nil {
		return m.CompanyIssued
	}
	return ""
}

func (m *Film) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Film) GetRatingFinal() float32 {
	if m != nil {
		return m.RatingFinal
	}
	return 0
}

func (m *Film) GetIs3D() int64 {
	if m != nil {
		return m.Is3D
	}
	return 0
}

func (m *Film) GetIsDMAX() int64 {
	if m != nil {
		return m.IsDMAX
	}
	return 0
}

func (m *Film) GetIsFilter() int64 {
	if m != nil {
		return m.IsFilter
	}
	return 0
}

func (m *Film) GetIsHot() int64 {
	if m != nil {
		return m.IsHot
	}
	return 0
}

func (m *Film) GetIsIMAX() int64 {
	if m != nil {
		return m.IsIMAX
	}
	return 0
}

func (m *Film) GetIsIMAX3D() int64 {
	if m != nil {
		return m.IsIMAX3D
	}
	return 0
}

func (m *Film) GetIsNew() int64 {
	if m != nil {
		return m.IsNew
	}
	return 0
}

func (m *Film) GetIsTicking() int64 {
	if m != nil {
		return m.IsTicking
	}
	return 0
}

func (m *Film) GetRDay() int64 {
	if m != nil {
		return m.RDay
	}
	return 0
}

func (m *Film) GetRMonth() int64 {
	if m != nil {
		return m.RMonth
	}
	return 0
}

func (m *Film) GetRYear() int64 {
	if m != nil {
		return m.RYear
	}
	return 0
}

func (m *Film) GetActorNames() []string {
	if m != nil {
		return m.ActorNames
	}
	return nil
}

func (m *Film) GetRYMD() string {
	if m != nil {
		return m.RYMD
	}
	return ""
}

type AllUsersReq struct {
	Page    int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	AdminID int64 `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *AllUsersReq) Reset()                    { *m = AllUsersReq{} }
func (m *AllUsersReq) String() string            { return proto.CompactTextString(m) }
func (*AllUsersReq) ProtoMessage()               {}
func (*AllUsersReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *AllUsersReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllUsersReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type AllUsersRsp struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	Total int64   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *AllUsersRsp) Reset()                    { *m = AllUsersRsp{} }
func (m *AllUsersRsp) String() string            { return proto.CompactTextString(m) }
func (*AllUsersRsp) ProtoMessage()               {}
func (*AllUsersRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *AllUsersRsp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AllUsersRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type User struct {
	UserId   int64  `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
	CreateAt string `protobuf:"bytes,4,opt,name=CreateAt" json:"CreateAt,omitempty"`
	Email    string `protobuf:"bytes,5,opt,name=Email" json:"Email,omitempty"`
	Phone    string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AllAdminUsersReq struct {
	Page    int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	AdminID int64 `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *AllAdminUsersReq) Reset()                    { *m = AllAdminUsersReq{} }
func (m *AllAdminUsersReq) String() string            { return proto.CompactTextString(m) }
func (*AllAdminUsersReq) ProtoMessage()               {}
func (*AllAdminUsersReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *AllAdminUsersReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllAdminUsersReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type AllAdminUsersRsp struct {
	AdminUsers []*AdminUser `protobuf:"bytes,1,rep,name=adminUsers" json:"adminUsers,omitempty"`
	Total      int64        `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *AllAdminUsersRsp) Reset()                    { *m = AllAdminUsersRsp{} }
func (m *AllAdminUsersRsp) String() string            { return proto.CompactTextString(m) }
func (*AllAdminUsersRsp) ProtoMessage()               {}
func (*AllAdminUsersRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *AllAdminUsersRsp) GetAdminUsers() []*AdminUser {
	if m != nil {
		return m.AdminUsers
	}
	return nil
}

func (m *AllAdminUsersRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AdminUser struct {
	AuID               int64  `protobuf:"varint,1,opt,name=AuID" json:"AuID,omitempty"`
	AdminName          string `protobuf:"bytes,2,opt,name=AdminName" json:"AdminName,omitempty"`
	AdminPassword      string `protobuf:"bytes,3,opt,name=AdminPassword" json:"AdminPassword,omitempty"`
	AdminCinemaID      int64  `protobuf:"varint,4,opt,name=AdminCinemaID" json:"AdminCinemaID,omitempty"`
	AdminLastLoginTime string `protobuf:"bytes,5,opt,name=AdminLastLoginTime" json:"AdminLastLoginTime,omitempty"`
	AdminNum           int64  `protobuf:"varint,6,opt,name=AdminNum" json:"AdminNum,omitempty"`
}

func (m *AdminUser) Reset()                    { *m = AdminUser{} }
func (m *AdminUser) String() string            { return proto.CompactTextString(m) }
func (*AdminUser) ProtoMessage()               {}
func (*AdminUser) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *AdminUser) GetAuID() int64 {
	if m != nil {
		return m.AuID
	}
	return 0
}

func (m *AdminUser) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func (m *AdminUser) GetAdminPassword() string {
	if m != nil {
		return m.AdminPassword
	}
	return ""
}

func (m *AdminUser) GetAdminCinemaID() int64 {
	if m != nil {
		return m.AdminCinemaID
	}
	return 0
}

func (m *AdminUser) GetAdminLastLoginTime() string {
	if m != nil {
		return m.AdminLastLoginTime
	}
	return ""
}

func (m *AdminUser) GetAdminNum() int64 {
	if m != nil {
		return m.AdminNum
	}
	return 0
}

type AllCommentsReq struct {
	Page    int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	AdminID int64 `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *AllCommentsReq) Reset()                    { *m = AllCommentsReq{} }
func (m *AllCommentsReq) String() string            { return proto.CompactTextString(m) }
func (*AllCommentsReq) ProtoMessage()               {}
func (*AllCommentsReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *AllCommentsReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllCommentsReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type AllCommentsRsp struct {
	Comments []*Comment `protobuf:"bytes,1,rep,name=comments" json:"comments,omitempty"`
	Total    int64      `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *AllCommentsRsp) Reset()                    { *m = AllCommentsRsp{} }
func (m *AllCommentsRsp) String() string            { return proto.CompactTextString(m) }
func (*AllCommentsRsp) ProtoMessage()               {}
func (*AllCommentsRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *AllCommentsRsp) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *AllCommentsRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Comment struct {
	CommentID int64  `protobuf:"varint,1,opt,name=commentID" json:"commentID,omitempty"`
	FilmID    int64  `protobuf:"varint,2,opt,name=filmID" json:"filmID,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	HeadImg   string `protobuf:"bytes,5,opt,name=headImg" json:"headImg,omitempty"`
	NickName  string `protobuf:"bytes,6,opt,name=nickName" json:"nickName,omitempty"`
	CreateAt  string `protobuf:"bytes,7,opt,name=createAt" json:"createAt,omitempty"`
	UpNum     int64  `protobuf:"varint,8,opt,name=upNum" json:"upNum,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *Comment) GetCommentID() int64 {
	if m != nil {
		return m.CommentID
	}
	return 0
}

func (m *Comment) GetFilmID() int64 {
	if m != nil {
		return m.FilmID
	}
	return 0
}

func (m *Comment) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *Comment) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Comment) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Comment) GetUpNum() int64 {
	if m != nil {
		return m.UpNum
	}
	return 0
}

type AllOrdersReq struct {
	Page    int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	AdminID int64 `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *AllOrdersReq) Reset()                    { *m = AllOrdersReq{} }
func (m *AllOrdersReq) String() string            { return proto.CompactTextString(m) }
func (*AllOrdersReq) ProtoMessage()               {}
func (*AllOrdersReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *AllOrdersReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllOrdersReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type AllOrdersRsp struct {
	Orders []*OrderAll `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
	Total  int64       `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *AllOrdersRsp) Reset()                    { *m = AllOrdersRsp{} }
func (m *AllOrdersRsp) String() string            { return proto.CompactTextString(m) }
func (*AllOrdersRsp) ProtoMessage()               {}
func (*AllOrdersRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *AllOrdersRsp) GetOrders() []*OrderAll {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *AllOrdersRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type OrderAll struct {
	OrderID     int64   `protobuf:"varint,1,opt,name=orderID" json:"orderID,omitempty"`
	OrderNum    string  `protobuf:"bytes,2,opt,name=orderNum" json:"orderNum,omitempty"`
	OrderStatus int64   `protobuf:"varint,3,opt,name=orderStatus" json:"orderStatus,omitempty"`
	OrderPrice  float32 `protobuf:"fixed32,4,opt,name=orderPrice" json:"orderPrice,omitempty"`
	CreateAt    string  `protobuf:"bytes,5,opt,name=createAt" json:"createAt,omitempty"`
	PayAt       string  `protobuf:"bytes,6,opt,name=payAt" json:"payAt,omitempty"`
	MhID        int64   `protobuf:"varint,7,opt,name=mhID" json:"mhID,omitempty"`
	OrderX      int64   `protobuf:"varint,8,opt,name=orderX" json:"orderX,omitempty"`
	OrderY      int64   `protobuf:"varint,9,opt,name=orderY" json:"orderY,omitempty"`
	UserID      int64   `protobuf:"varint,10,opt,name=userID" json:"userID,omitempty"`
	MovieID     int64   `protobuf:"varint,11,opt,name=movieID" json:"movieID,omitempty"`
	OrderScore  int64   `protobuf:"varint,12,opt,name=orderScore" json:"orderScore,omitempty"`
	StartTime   string  `protobuf:"bytes,13,opt,name=startTime" json:"startTime,omitempty"`
	EndTime     string  `protobuf:"bytes,14,opt,name=endTime" json:"endTime,omitempty"`
}

func (m *OrderAll) Reset()                    { *m = OrderAll{} }
func (m *OrderAll) String() string            { return proto.CompactTextString(m) }
func (*OrderAll) ProtoMessage()               {}
func (*OrderAll) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *OrderAll) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *OrderAll) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *OrderAll) GetOrderStatus() int64 {
	if m != nil {
		return m.OrderStatus
	}
	return 0
}

func (m *OrderAll) GetOrderPrice() float32 {
	if m != nil {
		return m.OrderPrice
	}
	return 0
}

func (m *OrderAll) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *OrderAll) GetPayAt() string {
	if m != nil {
		return m.PayAt
	}
	return ""
}

func (m *OrderAll) GetMhID() int64 {
	if m != nil {
		return m.MhID
	}
	return 0
}

func (m *OrderAll) GetOrderX() int64 {
	if m != nil {
		return m.OrderX
	}
	return 0
}

func (m *OrderAll) GetOrderY() int64 {
	if m != nil {
		return m.OrderY
	}
	return 0
}

func (m *OrderAll) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *OrderAll) GetMovieID() int64 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *OrderAll) GetOrderScore() int64 {
	if m != nil {
		return m.OrderScore
	}
	return 0
}

func (m *OrderAll) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *OrderAll) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type AllAddressReq struct {
	Page    int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	AdminID int64 `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *AllAddressReq) Reset()                    { *m = AllAddressReq{} }
func (m *AllAddressReq) String() string            { return proto.CompactTextString(m) }
func (*AllAddressReq) ProtoMessage()               {}
func (*AllAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *AllAddressReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AllAddressReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type AllAddressRsp struct {
	Places []*PlaceAll `protobuf:"bytes,1,rep,name=Places" json:"Places,omitempty"`
	Total  int64       `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *AllAddressRsp) Reset()                    { *m = AllAddressRsp{} }
func (m *AllAddressRsp) String() string            { return proto.CompactTextString(m) }
func (*AllAddressRsp) ProtoMessage()               {}
func (*AllAddressRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *AllAddressRsp) GetPlaces() []*PlaceAll {
	if m != nil {
		return m.Places
	}
	return nil
}

func (m *AllAddressRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PlaceAll struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Count       int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	PinyinFull  string `protobuf:"bytes,4,opt,name=pinyinFull" json:"pinyinFull,omitempty"`
	PinyinShort string `protobuf:"bytes,5,opt,name=pinyinShort" json:"pinyinShort,omitempty"`
}

func (m *PlaceAll) Reset()                    { *m = PlaceAll{} }
func (m *PlaceAll) String() string            { return proto.CompactTextString(m) }
func (*PlaceAll) ProtoMessage()               {}
func (*PlaceAll) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *PlaceAll) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlaceAll) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PlaceAll) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceAll) GetPinyinFull() string {
	if m != nil {
		return m.PinyinFull
	}
	return ""
}

func (m *PlaceAll) GetPinyinShort() string {
	if m != nil {
		return m.PinyinShort
	}
	return ""
}

type AddFilmReq struct {
	AdminID              int64    `protobuf:"varint,1,opt,name=adminID" json:"adminID,omitempty"`
	Img                  string   `protobuf:"bytes,2,opt,name=img" json:"img,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	IsSelectSeat         int64    `protobuf:"varint,4,opt,name=isSelectSeat" json:"isSelectSeat,omitempty"`
	FilmPrice            float32  `protobuf:"fixed32,5,opt,name=filmPrice" json:"filmPrice,omitempty"`
	FilmScreenwriter     string   `protobuf:"bytes,6,opt,name=filmScreenwriter" json:"filmScreenwriter,omitempty"`
	FilmDirector         string   `protobuf:"bytes,7,opt,name=filmDirector" json:"filmDirector,omitempty"`
	CommentNum           int64    `protobuf:"varint,8,opt,name=commentNum" json:"commentNum,omitempty"`
	TitleCn              string   `protobuf:"bytes,9,opt,name=titleCn" json:"titleCn,omitempty"`
	TitleEn              string   `protobuf:"bytes,10,opt,name=titleEn" json:"titleEn,omitempty"`
	IsSupportInlineWatch int64    `protobuf:"varint,11,opt,name=isSupportInlineWatch" json:"isSupportInlineWatch,omitempty"`
	CreateAt             string   `protobuf:"bytes,12,opt,name=createAt" json:"createAt,omitempty"`
	Type                 string   `protobuf:"bytes,13,opt,name=type" json:"type,omitempty"`
	FilmDrama            string   `protobuf:"bytes,14,opt,name=filmDrama" json:"filmDrama,omitempty"`
	CommonSpecial        string   `protobuf:"bytes,15,opt,name=commonSpecial" json:"commonSpecial,omitempty"`
	UserAccessTimes      int64    `protobuf:"varint,16,opt,name=userAccessTimes" json:"userAccessTimes,omitempty"`
	FilmBoxoffice        float32  `protobuf:"fixed32,17,opt,name=filmBoxoffice" json:"filmBoxoffice,omitempty"`
	WantedCount          int64    `protobuf:"varint,18,opt,name=wantedCount" json:"wantedCount,omitempty"`
	UserCommentTimes     int64    `protobuf:"varint,19,opt,name=userCommentTimes" json:"userCommentTimes,omitempty"`
	CompanyIssued        string   `protobuf:"bytes,20,opt,name=companyIssued" json:"companyIssued,omitempty"`
	Country              string   `protobuf:"bytes,21,opt,name=country" json:"country,omitempty"`
	RatingFinal          float32  `protobuf:"fixed32,22,opt,name=ratingFinal" json:"ratingFinal,omitempty"`
	Is3D                 int64    `protobuf:"varint,23,opt,name=is3D" json:"is3D,omitempty"`
	IsDMAX               int64    `protobuf:"varint,24,opt,name=isDMAX" json:"isDMAX,omitempty"`
	IsFilter             int64    `protobuf:"varint,25,opt,name=isFilter" json:"isFilter,omitempty"`
	IsHot                int64    `protobuf:"varint,26,opt,name=isHot" json:"isHot,omitempty"`
	IsIMAX               int64    `protobuf:"varint,27,opt,name=isIMAX" json:"isIMAX,omitempty"`
	IsIMAX3D             int64    `protobuf:"varint,28,opt,name=isIMAX3D" json:"isIMAX3D,omitempty"`
	IsNew                int64    `protobuf:"varint,29,opt,name=isNew" json:"isNew,omitempty"`
	IsTicking            int64    `protobuf:"varint,30,opt,name=isTicking" json:"isTicking,omitempty"`
	RDay                 int64    `protobuf:"varint,31,opt,name=rDay" json:"rDay,omitempty"`
	RMonth               int64    `protobuf:"varint,32,opt,name=rMonth" json:"rMonth,omitempty"`
	RYear                int64    `protobuf:"varint,33,opt,name=rYear" json:"rYear,omitempty"`
	ActorNames           []string `protobuf:"bytes,34,rep,name=actorNames" json:"actorNames,omitempty"`
}

func (m *AddFilmReq) Reset()                    { *m = AddFilmReq{} }
func (m *AddFilmReq) String() string            { return proto.CompactTextString(m) }
func (*AddFilmReq) ProtoMessage()               {}
func (*AddFilmReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *AddFilmReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

func (m *AddFilmReq) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *AddFilmReq) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *AddFilmReq) GetIsSelectSeat() int64 {
	if m != nil {
		return m.IsSelectSeat
	}
	return 0
}

func (m *AddFilmReq) GetFilmPrice() float32 {
	if m != nil {
		return m.FilmPrice
	}
	return 0
}

func (m *AddFilmReq) GetFilmScreenwriter() string {
	if m != nil {
		return m.FilmScreenwriter
	}
	return ""
}

func (m *AddFilmReq) GetFilmDirector() string {
	if m != nil {
		return m.FilmDirector
	}
	return ""
}

func (m *AddFilmReq) GetCommentNum() int64 {
	if m != nil {
		return m.CommentNum
	}
	return 0
}

func (m *AddFilmReq) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *AddFilmReq) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *AddFilmReq) GetIsSupportInlineWatch() int64 {
	if m != nil {
		return m.IsSupportInlineWatch
	}
	return 0
}

func (m *AddFilmReq) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *AddFilmReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddFilmReq) GetFilmDrama() string {
	if m != nil {
		return m.FilmDrama
	}
	return ""
}

func (m *AddFilmReq) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

func (m *AddFilmReq) GetUserAccessTimes() int64 {
	if m != nil {
		return m.UserAccessTimes
	}
	return 0
}

func (m *AddFilmReq) GetFilmBoxoffice() float32 {
	if m != nil {
		return m.FilmBoxoffice
	}
	return 0
}

func (m *AddFilmReq) GetWantedCount() int64 {
	if m != nil {
		return m.WantedCount
	}
	return 0
}

func (m *AddFilmReq) GetUserCommentTimes() int64 {
	if m != nil {
		return m.UserCommentTimes
	}
	return 0
}

func (m *AddFilmReq) GetCompanyIssued() string {
	if m != nil {
		return m.CompanyIssued
	}
	return ""
}

func (m *AddFilmReq) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AddFilmReq) GetRatingFinal() float32 {
	if m != nil {
		return m.RatingFinal
	}
	return 0
}

func (m *AddFilmReq) GetIs3D() int64 {
	if m != nil {
		return m.Is3D
	}
	return 0
}

func (m *AddFilmReq) GetIsDMAX() int64 {
	if m != nil {
		return m.IsDMAX
	}
	return 0
}

func (m *AddFilmReq) GetIsFilter() int64 {
	if m != nil {
		return m.IsFilter
	}
	return 0
}

func (m *AddFilmReq) GetIsHot() int64 {
	if m != nil {
		return m.IsHot
	}
	return 0
}

func (m *AddFilmReq) GetIsIMAX() int64 {
	if m != nil {
		return m.IsIMAX
	}
	return 0
}

func (m *AddFilmReq) GetIsIMAX3D() int64 {
	if m != nil {
		return m.IsIMAX3D
	}
	return 0
}

func (m *AddFilmReq) GetIsNew() int64 {
	if m != nil {
		return m.IsNew
	}
	return 0
}

func (m *AddFilmReq) GetIsTicking() int64 {
	if m != nil {
		return m.IsTicking
	}
	return 0
}

func (m *AddFilmReq) GetRDay() int64 {
	if m != nil {
		return m.RDay
	}
	return 0
}

func (m *AddFilmReq) GetRMonth() int64 {
	if m != nil {
		return m.RMonth
	}
	return 0
}

func (m *AddFilmReq) GetRYear() int64 {
	if m != nil {
		return m.RYear
	}
	return 0
}

func (m *AddFilmReq) GetActorNames() []string {
	if m != nil {
		return m.ActorNames
	}
	return nil
}

type AddFilmRsp struct {
}

func (m *AddFilmRsp) Reset()                    { *m = AddFilmRsp{} }
func (m *AddFilmRsp) String() string            { return proto.CompactTextString(m) }
func (*AddFilmRsp) ProtoMessage()               {}
func (*AddFilmRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

type UpdateFilmReq struct {
	MovieID       int64   `protobuf:"varint,1,opt,name=movieID" json:"movieID,omitempty"`
	Img           string  `protobuf:"bytes,2,opt,name=img" json:"img,omitempty"`
	Length        int64   `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	FilmPrice     float32 `protobuf:"fixed32,4,opt,name=filmPrice" json:"filmPrice,omitempty"`
	FilmDirector  string  `protobuf:"bytes,5,opt,name=filmDirector" json:"filmDirector,omitempty"`
	TitleCn       string  `protobuf:"bytes,6,opt,name=titleCn" json:"titleCn,omitempty"`
	TitleEn       string  `protobuf:"bytes,7,opt,name=titleEn" json:"titleEn,omitempty"`
	Type          string  `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	FilmDrama     string  `protobuf:"bytes,9,opt,name=filmDrama" json:"filmDrama,omitempty"`
	CommonSpecial string  `protobuf:"bytes,10,opt,name=commonSpecial" json:"commonSpecial,omitempty"`
	CompanyIssued string  `protobuf:"bytes,11,opt,name=companyIssued" json:"companyIssued,omitempty"`
	Country       string  `protobuf:"bytes,12,opt,name=country" json:"country,omitempty"`
	RDay          int64   `protobuf:"varint,13,opt,name=rDay" json:"rDay,omitempty"`
	RMonth        int64   `protobuf:"varint,14,opt,name=rMonth" json:"rMonth,omitempty"`
	RYear         int64   `protobuf:"varint,15,opt,name=rYear" json:"rYear,omitempty"`
	RYMD          string  `protobuf:"bytes,16,opt,name=rYMD" json:"rYMD,omitempty"`
	AdminID       int64   `protobuf:"varint,17,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *UpdateFilmReq) Reset()                    { *m = UpdateFilmReq{} }
func (m *UpdateFilmReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateFilmReq) ProtoMessage()               {}
func (*UpdateFilmReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *UpdateFilmReq) GetMovieID() int64 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *UpdateFilmReq) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *UpdateFilmReq) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *UpdateFilmReq) GetFilmPrice() float32 {
	if m != nil {
		return m.FilmPrice
	}
	return 0
}

func (m *UpdateFilmReq) GetFilmDirector() string {
	if m != nil {
		return m.FilmDirector
	}
	return ""
}

func (m *UpdateFilmReq) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *UpdateFilmReq) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *UpdateFilmReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateFilmReq) GetFilmDrama() string {
	if m != nil {
		return m.FilmDrama
	}
	return ""
}

func (m *UpdateFilmReq) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

func (m *UpdateFilmReq) GetCompanyIssued() string {
	if m != nil {
		return m.CompanyIssued
	}
	return ""
}

func (m *UpdateFilmReq) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *UpdateFilmReq) GetRDay() int64 {
	if m != nil {
		return m.RDay
	}
	return 0
}

func (m *UpdateFilmReq) GetRMonth() int64 {
	if m != nil {
		return m.RMonth
	}
	return 0
}

func (m *UpdateFilmReq) GetRYear() int64 {
	if m != nil {
		return m.RYear
	}
	return 0
}

func (m *UpdateFilmReq) GetRYMD() string {
	if m != nil {
		return m.RYMD
	}
	return ""
}

func (m *UpdateFilmReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type UpdateFilmRsp struct {
}

func (m *UpdateFilmRsp) Reset()                    { *m = UpdateFilmRsp{} }
func (m *UpdateFilmRsp) String() string            { return proto.CompactTextString(m) }
func (*UpdateFilmRsp) ProtoMessage()               {}
func (*UpdateFilmRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

type DeleteFilmReq struct {
	MovieID int64 `protobuf:"varint,1,opt,name=movieID" json:"movieID,omitempty"`
	AdminID int64 `protobuf:"varint,2,opt,name=adminID" json:"adminID,omitempty"`
}

func (m *DeleteFilmReq) Reset()                    { *m = DeleteFilmReq{} }
func (m *DeleteFilmReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteFilmReq) ProtoMessage()               {}
func (*DeleteFilmReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *DeleteFilmReq) GetMovieID() int64 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *DeleteFilmReq) GetAdminID() int64 {
	if m != nil {
		return m.AdminID
	}
	return 0
}

type DeleteFilmRsp struct {
}

func (m *DeleteFilmRsp) Reset()                    { *m = DeleteFilmRsp{} }
func (m *DeleteFilmRsp) String() string            { return proto.CompactTextString(m) }
func (*DeleteFilmRsp) ProtoMessage()               {}
func (*DeleteFilmRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func init() {
	proto.RegisterType((*UserLoginReq)(nil), "pb.UserLoginReq")
	proto.RegisterType((*UserLoginRsp)(nil), "pb.UserLoginRsp")
	proto.RegisterType((*UpdateMessageReq)(nil), "pb.UpdateMessageReq")
	proto.RegisterType((*UpdateMessageRsp)(nil), "pb.UpdateMessageRsp")
	proto.RegisterType((*AllFilmsReq)(nil), "pb.AllFilmsReq")
	proto.RegisterType((*AllFilmsRsp)(nil), "pb.AllFilmsRsp")
	proto.RegisterType((*Film)(nil), "pb.Film")
	proto.RegisterType((*AllUsersReq)(nil), "pb.AllUsersReq")
	proto.RegisterType((*AllUsersRsp)(nil), "pb.AllUsersRsp")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*AllAdminUsersReq)(nil), "pb.AllAdminUsersReq")
	proto.RegisterType((*AllAdminUsersRsp)(nil), "pb.AllAdminUsersRsp")
	proto.RegisterType((*AdminUser)(nil), "pb.AdminUser")
	proto.RegisterType((*AllCommentsReq)(nil), "pb.AllCommentsReq")
	proto.RegisterType((*AllCommentsRsp)(nil), "pb.AllCommentsRsp")
	proto.RegisterType((*Comment)(nil), "pb.Comment")
	proto.RegisterType((*AllOrdersReq)(nil), "pb.AllOrdersReq")
	proto.RegisterType((*AllOrdersRsp)(nil), "pb.AllOrdersRsp")
	proto.RegisterType((*OrderAll)(nil), "pb.OrderAll")
	proto.RegisterType((*AllAddressReq)(nil), "pb.AllAddressReq")
	proto.RegisterType((*AllAddressRsp)(nil), "pb.AllAddressRsp")
	proto.RegisterType((*PlaceAll)(nil), "pb.PlaceAll")
	proto.RegisterType((*AddFilmReq)(nil), "pb.AddFilmReq")
	proto.RegisterType((*AddFilmRsp)(nil), "pb.AddFilmRsp")
	proto.RegisterType((*UpdateFilmReq)(nil), "pb.UpdateFilmReq")
	proto.RegisterType((*UpdateFilmRsp)(nil), "pb.UpdateFilmRsp")
	proto.RegisterType((*DeleteFilmReq)(nil), "pb.DeleteFilmReq")
	proto.RegisterType((*DeleteFilmRsp)(nil), "pb.DeleteFilmRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CMSServiceExt service

type CMSServiceExtClient interface {
	UserLogin(ctx context.Context, in *UserLoginReq, opts ...client.CallOption) (*UserLoginRsp, error)
	UpdateMessage(ctx context.Context, in *UpdateMessageReq, opts ...client.CallOption) (*UpdateMessageRsp, error)
	AllFilms(ctx context.Context, in *AllFilmsReq, opts ...client.CallOption) (*AllFilmsRsp, error)
	UpdateFilm(ctx context.Context, in *UpdateFilmReq, opts ...client.CallOption) (*UpdateFilmRsp, error)
	DeleteFilm(ctx context.Context, in *DeleteFilmReq, opts ...client.CallOption) (*DeleteFilmRsp, error)
	AllUsers(ctx context.Context, in *AllUsersReq, opts ...client.CallOption) (*AllUsersRsp, error)
	AllAdminUsers(ctx context.Context, in *AllAdminUsersReq, opts ...client.CallOption) (*AllAdminUsersRsp, error)
	AllComments(ctx context.Context, in *AllCommentsReq, opts ...client.CallOption) (*AllCommentsRsp, error)
	AllOrders(ctx context.Context, in *AllOrdersReq, opts ...client.CallOption) (*AllOrdersRsp, error)
	AllAddress(ctx context.Context, in *AllAddressReq, opts ...client.CallOption) (*AllAddressRsp, error)
	AddFilm(ctx context.Context, in *AddFilmReq, opts ...client.CallOption) (*AddFilmRsp, error)
}

type cMSServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewCMSServiceExtClient(serviceName string, c client.Client) CMSServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &cMSServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *cMSServiceExtClient) UserLogin(ctx context.Context, in *UserLoginReq, opts ...client.CallOption) (*UserLoginRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.UserLogin", in)
	out := new(UserLoginRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) UpdateMessage(ctx context.Context, in *UpdateMessageReq, opts ...client.CallOption) (*UpdateMessageRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.UpdateMessage", in)
	out := new(UpdateMessageRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) AllFilms(ctx context.Context, in *AllFilmsReq, opts ...client.CallOption) (*AllFilmsRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.AllFilms", in)
	out := new(AllFilmsRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) UpdateFilm(ctx context.Context, in *UpdateFilmReq, opts ...client.CallOption) (*UpdateFilmRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.UpdateFilm", in)
	out := new(UpdateFilmRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) DeleteFilm(ctx context.Context, in *DeleteFilmReq, opts ...client.CallOption) (*DeleteFilmRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.DeleteFilm", in)
	out := new(DeleteFilmRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) AllUsers(ctx context.Context, in *AllUsersReq, opts ...client.CallOption) (*AllUsersRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.AllUsers", in)
	out := new(AllUsersRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) AllAdminUsers(ctx context.Context, in *AllAdminUsersReq, opts ...client.CallOption) (*AllAdminUsersRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.AllAdminUsers", in)
	out := new(AllAdminUsersRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) AllComments(ctx context.Context, in *AllCommentsReq, opts ...client.CallOption) (*AllCommentsRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.AllComments", in)
	out := new(AllCommentsRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) AllOrders(ctx context.Context, in *AllOrdersReq, opts ...client.CallOption) (*AllOrdersRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.AllOrders", in)
	out := new(AllOrdersRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) AllAddress(ctx context.Context, in *AllAddressReq, opts ...client.CallOption) (*AllAddressRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.AllAddress", in)
	out := new(AllAddressRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMSServiceExtClient) AddFilm(ctx context.Context, in *AddFilmReq, opts ...client.CallOption) (*AddFilmRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.AddFilm", in)
	out := new(AddFilmRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CMSServiceExt service

type CMSServiceExtHandler interface {
	UserLogin(context.Context, *UserLoginReq, *UserLoginRsp) error
	UpdateMessage(context.Context, *UpdateMessageReq, *UpdateMessageRsp) error
	AllFilms(context.Context, *AllFilmsReq, *AllFilmsRsp) error
	UpdateFilm(context.Context, *UpdateFilmReq, *UpdateFilmRsp) error
	DeleteFilm(context.Context, *DeleteFilmReq, *DeleteFilmRsp) error
	AllUsers(context.Context, *AllUsersReq, *AllUsersRsp) error
	AllAdminUsers(context.Context, *AllAdminUsersReq, *AllAdminUsersRsp) error
	AllComments(context.Context, *AllCommentsReq, *AllCommentsRsp) error
	AllOrders(context.Context, *AllOrdersReq, *AllOrdersRsp) error
	AllAddress(context.Context, *AllAddressReq, *AllAddressRsp) error
	AddFilm(context.Context, *AddFilmReq, *AddFilmRsp) error
}

func RegisterCMSServiceExtHandler(s server.Server, hdlr CMSServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CMSServiceExt{hdlr}, opts...))
}

type CMSServiceExt struct {
	CMSServiceExtHandler
}

func (h *CMSServiceExt) UserLogin(ctx context.Context, in *UserLoginReq, out *UserLoginRsp) error {
	return h.CMSServiceExtHandler.UserLogin(ctx, in, out)
}

func (h *CMSServiceExt) UpdateMessage(ctx context.Context, in *UpdateMessageReq, out *UpdateMessageRsp) error {
	return h.CMSServiceExtHandler.UpdateMessage(ctx, in, out)
}

func (h *CMSServiceExt) AllFilms(ctx context.Context, in *AllFilmsReq, out *AllFilmsRsp) error {
	return h.CMSServiceExtHandler.AllFilms(ctx, in, out)
}

func (h *CMSServiceExt) UpdateFilm(ctx context.Context, in *UpdateFilmReq, out *UpdateFilmRsp) error {
	return h.CMSServiceExtHandler.UpdateFilm(ctx, in, out)
}

func (h *CMSServiceExt) DeleteFilm(ctx context.Context, in *DeleteFilmReq, out *DeleteFilmRsp) error {
	return h.CMSServiceExtHandler.DeleteFilm(ctx, in, out)
}

func (h *CMSServiceExt) AllUsers(ctx context.Context, in *AllUsersReq, out *AllUsersRsp) error {
	return h.CMSServiceExtHandler.AllUsers(ctx, in, out)
}

func (h *CMSServiceExt) AllAdminUsers(ctx context.Context, in *AllAdminUsersReq, out *AllAdminUsersRsp) error {
	return h.CMSServiceExtHandler.AllAdminUsers(ctx, in, out)
}

func (h *CMSServiceExt) AllComments(ctx context.Context, in *AllCommentsReq, out *AllCommentsRsp) error {
	return h.CMSServiceExtHandler.AllComments(ctx, in, out)
}

func (h *CMSServiceExt) AllOrders(ctx context.Context, in *AllOrdersReq, out *AllOrdersRsp) error {
	return h.CMSServiceExtHandler.AllOrders(ctx, in, out)
}

func (h *CMSServiceExt) AllAddress(ctx context.Context, in *AllAddressReq, out *AllAddressRsp) error {
	return h.CMSServiceExtHandler.AllAddress(ctx, in, out)
}

func (h *CMSServiceExt) AddFilm(ctx context.Context, in *AddFilmReq, out *AddFilmRsp) error {
	return h.CMSServiceExtHandler.AddFilm(ctx, in, out)
}

func init() { proto.RegisterFile("cms.ext.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4f, 0x6f, 0x1b, 0x37,
	0x16, 0x5f, 0x59, 0xb2, 0x2d, 0xd1, 0x96, 0xed, 0x70, 0xbd, 0x59, 0xae, 0x36, 0x9b, 0xf5, 0xce,
	0x06, 0x58, 0x63, 0x8b, 0x1a, 0x48, 0x52, 0xa0, 0x87, 0x36, 0x41, 0x55, 0xc9, 0x46, 0xd4, 0xc6,
	0x4e, 0x30, 0x4a, 0x90, 0xf8, 0x48, 0x8f, 0x18, 0x99, 0xcd, 0x0c, 0x67, 0x32, 0xa4, 0xe2, 0xf8,
	0xda, 0x43, 0x3e, 0x41, 0xcf, 0xfd, 0x4e, 0x3d, 0x14, 0x3d, 0xf4, 0xcb, 0x14, 0xef, 0x91, 0x9c,
	0x3f, 0xb2, 0x84, 0x14, 0xee, 0xad, 0xc8, 0x49, 0xfc, 0xfd, 0xf8, 0xf8, 0x86, 0x7c, 0xff, 0xf8,
	0x28, 0xd2, 0x8d, 0x12, 0x7d, 0x20, 0xde, 0x99, 0x83, 0x2c, 0x4f, 0x4d, 0x4a, 0x57, 0xb2, 0xb3,
	0xe0, 0x21, 0xd9, 0x7c, 0xae, 0x45, 0xfe, 0x38, 0x9d, 0x4a, 0x15, 0x8a, 0x37, 0x94, 0x92, 0xd6,
	0x4c, 0x8b, 0x9c, 0x35, 0xf6, 0x1a, 0xfb, 0x9d, 0x10, 0xc7, 0xb4, 0x47, 0xda, 0x19, 0xd7, 0xfa,
	0x22, 0xcd, 0x27, 0x6c, 0x05, 0xf9, 0x02, 0x07, 0x8f, 0xaa, 0xeb, 0x75, 0x46, 0x19, 0x59, 0xe7,
	0x93, 0x44, 0xaa, 0xd1, 0x10, 0x45, 0x9b, 0xa1, 0x87, 0xf4, 0x36, 0x21, 0x91, 0x54, 0x22, 0xe1,
	0x27, 0x3c, 0x11, 0xac, 0x89, 0x7a, 0x2a, 0x4c, 0x70, 0x42, 0x76, 0x9e, 0x67, 0x13, 0x6e, 0xc4,
	0xb1, 0xd0, 0x9a, 0x4f, 0x05, 0xec, 0x66, 0x97, 0xac, 0x1a, 0x7e, 0x16, 0x0b, 0xb7, 0x1d, 0x0b,
	0x60, 0x8f, 0xdf, 0xe9, 0x54, 0xb9, 0xbd, 0xe0, 0x98, 0xee, 0x90, 0xa6, 0x9a, 0x25, 0x4e, 0x2d,
	0x0c, 0x03, 0x3a, 0xaf, 0x4f, 0x67, 0xc1, 0x17, 0x64, 0xa3, 0x1f, 0xc7, 0x47, 0x32, 0x4e, 0xb4,
	0x3b, 0x6c, 0xc6, 0xa7, 0x56, 0x7b, 0x33, 0xc4, 0xf1, 0xf2, 0x03, 0x04, 0x83, 0xca, 0x62, 0x9d,
	0xe1, 0xde, 0x52, 0xc3, 0x63, 0xb7, 0xda, 0x02, 0x7a, 0x9b, 0xac, 0xbe, 0x02, 0x09, 0xb6, 0xb2,
	0xd7, 0xdc, 0xdf, 0xb8, 0xd7, 0x3e, 0xc8, 0xce, 0x0e, 0x60, 0x49, 0x68, 0xe9, 0xe0, 0x87, 0x36,
	0x69, 0x01, 0x86, 0xef, 0x24, 0xe9, 0x5b, 0x29, 0x46, 0x43, 0xa7, 0xc0, 0x43, 0x38, 0x8a, 0x4c,
	0xa6, 0xee, 0x74, 0x30, 0xa4, 0x37, 0xc9, 0x5a, 0x2c, 0xd4, 0xd4, 0x9c, 0xe3, 0xf9, 0x9a, 0xa1,
	0x43, 0x34, 0x20, 0x9b, 0x52, 0x8f, 0x45, 0x2c, 0x22, 0x33, 0x16, 0xdc, 0xb0, 0x16, 0xce, 0xd6,
	0x38, 0x7a, 0x8b, 0x74, 0xe0, 0xcb, 0x4f, 0x73, 0x19, 0x09, 0xb6, 0xba, 0xd7, 0xd8, 0x5f, 0x09,
	0x4b, 0x82, 0xfe, 0x9f, 0xec, 0x00, 0x18, 0x47, 0xb9, 0x10, 0xea, 0x22, 0x97, 0x46, 0xe4, 0x6c,
	0x0d, 0x3f, 0x7c, 0x85, 0x87, 0xaf, 0x01, 0x37, 0x94, 0xb9, 0x88, 0x4c, 0x9a, 0xb3, 0x75, 0x94,
	0xab, 0x71, 0xe8, 0xe4, 0x34, 0x49, 0x84, 0x32, 0x27, 0xb3, 0x84, 0xb5, 0x71, 0x3f, 0x15, 0x06,
	0x4e, 0x6d, 0xa4, 0x89, 0xc5, 0x40, 0xb1, 0x0e, 0x2e, 0xf7, 0xb0, 0x98, 0x39, 0x54, 0x8c, 0x54,
	0x66, 0x0e, 0x15, 0xbd, 0x47, 0x76, 0xa5, 0x1e, 0xcf, 0xb2, 0x2c, 0xcd, 0xcd, 0x48, 0xc5, 0x52,
	0x89, 0x17, 0xdc, 0x44, 0xe7, 0x6c, 0x03, 0xb5, 0x2f, 0x9c, 0x83, 0x90, 0x8d, 0x72, 0xc1, 0x8d,
	0xe8, 0x1b, 0xb6, 0x69, 0x43, 0xd6, 0x63, 0xf0, 0xba, 0xb9, 0xcc, 0x04, 0xeb, 0xda, 0xf0, 0x81,
	0xb1, 0xb7, 0xd2, 0x30, 0xe7, 0x09, 0x67, 0x5b, 0x38, 0x51, 0x12, 0xf4, 0x0e, 0xe9, 0xc2, 0x19,
	0x52, 0x35, 0xce, 0x44, 0x24, 0x79, 0xcc, 0xb6, 0x51, 0xa2, 0x4e, 0xd2, 0x7d, 0xb2, 0x0d, 0xe9,
	0xd2, 0x8f, 0x22, 0xa1, 0xf5, 0x33, 0x99, 0x08, 0xcd, 0x76, 0x70, 0x8b, 0xf3, 0x34, 0xe8, 0x03,
	0xe5, 0x5f, 0xa7, 0xef, 0xd2, 0x57, 0xaf, 0xc0, 0x2f, 0x37, 0xd0, 0x2f, 0x75, 0x92, 0xee, 0x91,
	0x8d, 0x0b, 0xae, 0x8c, 0x98, 0x0c, 0xd2, 0x99, 0x32, 0x8c, 0xa2, 0xae, 0x2a, 0x05, 0xde, 0x03,
	0xd5, 0x03, 0x6b, 0x5f, 0xfb, 0xc9, 0xbf, 0xa2, 0xd8, 0x15, 0xde, 0x9d, 0x21, 0xe3, 0xea, 0x72,
	0xa4, 0xf5, 0x4c, 0x4c, 0xd8, 0x6e, 0x71, 0x86, 0x92, 0x04, 0x2f, 0x44, 0xa0, 0x3a, 0xbf, 0x64,
	0x7f, 0xb3, 0x5e, 0x70, 0x10, 0x76, 0x93, 0x73, 0x23, 0xd5, 0xf4, 0x48, 0x2a, 0x1e, 0xb3, 0x9b,
	0xb8, 0xe3, 0x2a, 0x05, 0x76, 0x95, 0xfa, 0xfe, 0x90, 0xfd, 0xdd, 0x66, 0x13, 0x8c, 0x21, 0x72,
	0xa5, 0x1e, 0x1e, 0xf7, 0x5f, 0x32, 0x66, 0x23, 0xd7, 0x22, 0xf0, 0x8f, 0xd4, 0x47, 0x32, 0x86,
	0x78, 0xfb, 0x07, 0xce, 0x14, 0x18, 0x12, 0x4b, 0xea, 0x47, 0xa9, 0x61, 0x3d, 0x9b, 0x58, 0x08,
	0xac, 0xa6, 0x11, 0x68, 0xfa, 0xa7, 0xd7, 0x34, 0x2a, 0x34, 0xc1, 0xe8, 0xfe, 0x90, 0xdd, 0xf2,
	0x9a, 0x2c, 0xb6, 0x9a, 0x4e, 0xc4, 0x05, 0xfb, 0x97, 0xd7, 0x74, 0x22, 0x2e, 0xc0, 0xd7, 0x52,
	0x3f, 0x93, 0xd1, 0x6b, 0xa9, 0xa6, 0xec, 0x36, 0xce, 0x94, 0x04, 0x9c, 0x22, 0x1f, 0xf2, 0x4b,
	0xf6, 0x6f, 0x7b, 0x0a, 0x18, 0xc3, 0xb7, 0xf3, 0xe3, 0x54, 0x99, 0x73, 0xb6, 0x67, 0xbf, 0x6d,
	0x11, 0xe8, 0xcf, 0x4f, 0x05, 0xcf, 0xd9, 0x7f, 0xac, 0x7e, 0x04, 0x90, 0x03, 0x1c, 0x92, 0x01,
	0xaa, 0x9a, 0x66, 0xc1, 0x5e, 0x13, 0x0a, 0x5d, 0xc9, 0xe0, 0x17, 0x4e, 0x8f, 0x87, 0xec, 0xbf,
	0x36, 0xfe, 0x60, 0xec, 0x0a, 0x13, 0x54, 0xd2, 0x6b, 0x17, 0x26, 0xbb, 0x58, 0x67, 0x50, 0x82,
	0xc0, 0xfb, 0x9a, 0x35, 0xca, 0x12, 0x04, 0x93, 0xa1, 0xa5, 0xcb, 0xc2, 0xb5, 0x52, 0x29, 0x5c,
	0xc1, 0x8f, 0x0d, 0xd2, 0x02, 0x29, 0x38, 0x2c, 0xfc, 0x8e, 0x26, 0xee, 0xeb, 0x0e, 0x81, 0xa1,
	0x61, 0x84, 0xd5, 0xdb, 0xdd, 0x02, 0x1e, 0xc3, 0xdc, 0x53, 0x7f, 0x43, 0xd8, 0x12, 0x5c, 0x60,
	0x98, 0x1b, 0xf8, 0x54, 0x6c, 0xd9, 0x39, 0x8f, 0x61, 0x2b, 0x87, 0x09, 0x97, 0x31, 0x16, 0xa6,
	0x4e, 0x68, 0x01, 0xb0, 0xd9, 0x79, 0xaa, 0x84, 0xab, 0x44, 0x16, 0x04, 0x5f, 0x91, 0x9d, 0x7e,
	0x1c, 0xf7, 0xe1, 0xcc, 0xd7, 0xb4, 0xd3, 0x8b, 0x79, 0x0d, 0x3a, 0xa3, 0x9f, 0x12, 0xc2, 0x0b,
	0xc2, 0x59, 0xac, 0x0b, 0x16, 0x2b, 0xc4, 0xc2, 0x8a, 0xc0, 0x12, 0xdb, 0xfd, 0xdc, 0x20, 0x9d,
	0x42, 0x1e, 0x36, 0xd5, 0x9f, 0x15, 0x65, 0x1d, 0xc7, 0x10, 0x73, 0x28, 0x50, 0xb1, 0x5e, 0x49,
	0x40, 0x6e, 0x22, 0x98, 0xb3, 0x61, 0x9d, 0x2c, 0xa4, 0x06, 0x78, 0x67, 0x8e, 0x86, 0xae, 0xdc,
	0xd7, 0x49, 0x7a, 0x40, 0x28, 0x12, 0x8f, 0xb9, 0x36, 0x78, 0x2b, 0x43, 0xfa, 0x3b, 0xfb, 0x2e,
	0x98, 0x01, 0xf7, 0xd8, 0x8d, 0xcc, 0x12, 0xb4, 0x77, 0x33, 0x2c, 0x70, 0xf0, 0x90, 0x6c, 0xf5,
	0xe3, 0xd8, 0x95, 0x91, 0x6b, 0x18, 0xfc, 0x49, 0x7d, 0xbd, 0xce, 0xe8, 0xff, 0x48, 0xdb, 0xdd,
	0x06, 0xde, 0xd8, 0x1b, 0x60, 0x6c, 0x27, 0x12, 0x16, 0x93, 0x4b, 0x0c, 0xfd, 0x4b, 0x83, 0xac,
	0x3b, 0x59, 0x30, 0xa9, 0x93, 0x2e, 0x6c, 0x5d, 0x12, 0x10, 0xc5, 0x50, 0x4d, 0x8b, 0x3d, 0x39,
	0x84, 0x7a, 0xe1, 0x5e, 0x71, 0x26, 0xb6, 0xc0, 0x96, 0x3d, 0x65, 0x84, 0xf2, 0x21, 0xea, 0x21,
	0xcc, 0x9c, 0x0b, 0x3e, 0x19, 0x25, 0x53, 0x67, 0x43, 0x0f, 0xc1, 0x70, 0x4a, 0x46, 0xaf, 0xd1,
	0xa3, 0x36, 0x50, 0x0b, 0x5c, 0xbb, 0x7e, 0xd6, 0xe7, 0xae, 0x9f, 0x5d, 0xb2, 0x3a, 0xcb, 0xca,
	0xdb, 0xd1, 0x82, 0xe0, 0x4b, 0xb2, 0xd9, 0x8f, 0xe3, 0x27, 0xf9, 0xe4, 0x5a, 0x91, 0xfd, 0x4d,
	0x75, 0xb5, 0xce, 0xe8, 0x1d, 0xb2, 0x96, 0x22, 0x70, 0x46, 0xde, 0x04, 0x23, 0xe3, 0x74, 0x3f,
	0x8e, 0x43, 0x37, 0xb7, 0xc4, 0xc6, 0xdf, 0x37, 0x49, 0xdb, 0x8b, 0xc2, 0x27, 0x51, 0xb8, 0xec,
	0x52, 0x1c, 0x84, 0x23, 0xe2, 0x10, 0x4e, 0xe2, 0xca, 0x81, 0xc7, 0x70, 0x57, 0xe0, 0x78, 0x6c,
	0xb8, 0x99, 0x69, 0xd7, 0xb4, 0x54, 0x29, 0xa8, 0x91, 0x08, 0x6d, 0x5b, 0xd2, 0xc2, 0xcb, 0xa4,
	0xc2, 0xd4, 0x0c, 0xb8, 0x7a, 0xd5, 0x80, 0x19, 0xbf, 0xec, 0x9b, 0xa2, 0x3c, 0x00, 0x00, 0x83,
	0x25, 0xe7, 0xa3, 0x21, 0x9a, 0xbb, 0x19, 0xe2, 0x18, 0x82, 0x00, 0x75, 0xbe, 0x74, 0xb6, 0x76,
	0xa8, 0xe0, 0x4f, 0xb1, 0x09, 0xf1, 0xfc, 0x29, 0xf0, 0x50, 0x22, 0x47, 0x43, 0x6c, 0x41, 0x9a,
	0xa1, 0x43, 0xd5, 0x5e, 0x6d, 0xa3, 0xde, 0xab, 0xf9, 0x73, 0x8c, 0xa3, 0x34, 0x17, 0xd8, 0x69,
	0x34, 0xc3, 0x0a, 0x03, 0x41, 0xaa, 0x0d, 0xcf, 0xf1, 0x0e, 0x76, 0x0d, 0x47, 0x49, 0x80, 0x5e,
	0xa1, 0x26, 0x38, 0x67, 0x7b, 0x0e, 0x0f, 0x83, 0x07, 0xa4, 0x8b, 0xa5, 0x6a, 0x92, 0x0b, 0x7d,
	0x8d, 0x78, 0xf8, 0xb6, 0xb6, 0xdc, 0x06, 0xc4, 0xd3, 0x98, 0x47, 0xa2, 0x16, 0x10, 0xc8, 0x60,
	0x40, 0xd8, 0xb9, 0x25, 0x01, 0xf1, 0xbe, 0x41, 0xda, 0x5e, 0x94, 0x6e, 0x91, 0x15, 0xe9, 0x6f,
	0x86, 0x15, 0x39, 0x81, 0x25, 0xd8, 0x21, 0xf8, 0x25, 0x08, 0x60, 0xb7, 0xaa, 0xec, 0xf2, 0x71,
	0x0c, 0xa6, 0xca, 0xa4, 0xba, 0x94, 0xea, 0x68, 0x16, 0xc7, 0x2e, 0xcd, 0x2a, 0x0c, 0x04, 0x8d,
	0x45, 0xe3, 0xf3, 0x34, 0xf7, 0x5e, 0xaf, 0x52, 0xc1, 0xfb, 0x36, 0x21, 0xfd, 0xc9, 0x04, 0xdb,
	0x69, 0xf1, 0xa6, 0x7a, 0xfc, 0x46, 0xfd, 0xa9, 0xf1, 0xb1, 0x83, 0xfe, 0xd8, 0x41, 0x7f, 0xec,
	0xa0, 0xff, 0xb4, 0x1d, 0x74, 0xb0, 0x59, 0xd6, 0x01, 0x9d, 0x05, 0x3f, 0x35, 0x49, 0xd7, 0xbe,
	0xf4, 0x2b, 0x95, 0xe1, 0x0f, 0xbf, 0xad, 0x6b, 0x59, 0xdf, 0x9a, 0xcf, 0xfa, 0xf9, 0x4c, 0x5e,
	0x5d, 0x90, 0xc9, 0x95, 0x4c, 0x5d, 0x5b, 0x9a, 0xa9, 0xeb, 0xf5, 0x4c, 0xf5, 0x99, 0xd5, 0x5e,
	0x96, 0x59, 0x9d, 0x0f, 0x66, 0x16, 0x59, 0x94, 0x59, 0x57, 0x62, 0x77, 0xe3, 0x03, 0xb1, 0xbb,
	0x59, 0x8f, 0x5d, 0xef, 0xd3, 0xee, 0x42, 0x9f, 0x6e, 0x2d, 0xf6, 0xe9, 0x76, 0xd5, 0xa7, 0xfe,
	0xd5, 0xb3, 0x53, 0xbe, 0x7a, 0xaa, 0x15, 0xfc, 0x46, 0xfd, 0x02, 0xdb, 0xae, 0xb9, 0x54, 0x67,
	0xc1, 0x80, 0x74, 0x87, 0x22, 0x16, 0xbf, 0xc7, 0xc7, 0xcb, 0xaf, 0xc5, 0xed, 0x9a, 0x12, 0x9d,
	0xdd, 0xfb, 0xb5, 0x45, 0xba, 0x83, 0xe3, 0xf1, 0x58, 0xe4, 0x6f, 0x65, 0x24, 0x0e, 0xdf, 0x19,
	0x7a, 0x97, 0x74, 0x8a, 0xff, 0xb3, 0xe8, 0x8e, 0x7f, 0x3a, 0xf9, 0xbf, 0xc7, 0x7a, 0x73, 0x8c,
	0xce, 0x82, 0xbf, 0xd0, 0x07, 0x7e, 0xaf, 0xee, 0x8f, 0x26, 0xba, 0x8b, 0x42, 0x73, 0xff, 0x65,
	0xf5, 0x16, 0xb0, 0xb8, 0xfc, 0x80, 0xb4, 0xfd, 0xdf, 0x4a, 0x74, 0x1b, 0x5f, 0x1e, 0xe5, 0x3f,
	0x54, 0xbd, 0x3a, 0x81, 0xf2, 0x9f, 0x11, 0x52, 0x9a, 0x86, 0xde, 0x28, 0xb5, 0x3a, 0xcb, 0xf4,
	0xe6, 0x29, 0xbf, 0xaa, 0x3c, 0xba, 0x5d, 0x55, 0xb3, 0x67, 0x6f, 0x9e, 0xaa, 0xec, 0xcd, 0x3e,
	0x7d, 0xfc, 0x56, 0xfc, 0xe3, 0xab, 0x57, 0x27, 0xbc, 0x29, 0x6a, 0x2f, 0x2c, 0x6b, 0x8a, 0xf9,
	0x67, 0x5b, 0x6f, 0x01, 0x8b, 0xcb, 0x3f, 0xc7, 0x87, 0xac, 0x7f, 0x2f, 0x50, 0xea, 0xc4, 0x2a,
	0x0f, 0x90, 0xde, 0x15, 0x0e, 0x17, 0xde, 0x25, 0x9d, 0xa2, 0xff, 0xb5, 0x5e, 0xab, 0x36, 0xd3,
	0xbd, 0x39, 0xc6, 0x1b, 0xa4, 0x6c, 0x91, 0xac, 0x41, 0x6a, 0x1d, 0x57, 0x6f, 0x9e, 0xc2, 0x55,
	0x9f, 0x90, 0x75, 0x57, 0x79, 0xe8, 0x96, 0x7d, 0x25, 0xfa, 0x76, 0xa4, 0x57, 0xc3, 0x20, 0x7c,
	0xb6, 0x86, 0x7f, 0xb3, 0xde, 0xff, 0x2d, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x6d, 0x99, 0x82, 0x77,
	0x15, 0x00, 0x00,
}
