// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cms.ext.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserLoginReq struct {
}

func (m *UserLoginReq) Reset()                    { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string            { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()               {}
func (*UserLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type UserLoginRsp struct {
}

func (m *UserLoginRsp) Reset()                    { *m = UserLoginRsp{} }
func (m *UserLoginRsp) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRsp) ProtoMessage()               {}
func (*UserLoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func init() {
	proto.RegisterType((*UserLoginReq)(nil), "pb.UserLoginReq")
	proto.RegisterType((*UserLoginRsp)(nil), "pb.UserLoginRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CMSServiceExt service

type CMSServiceExtClient interface {
	UserLogin(ctx context.Context, in *UserLoginReq, opts ...client.CallOption) (*UserLoginRsp, error)
}

type cMSServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewCMSServiceExtClient(serviceName string, c client.Client) CMSServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &cMSServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *cMSServiceExtClient) UserLogin(ctx context.Context, in *UserLoginReq, opts ...client.CallOption) (*UserLoginRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CMSServiceExt.UserLogin", in)
	out := new(UserLoginRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CMSServiceExt service

type CMSServiceExtHandler interface {
	UserLogin(context.Context, *UserLoginReq, *UserLoginRsp) error
}

func RegisterCMSServiceExtHandler(s server.Server, hdlr CMSServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CMSServiceExt{hdlr}, opts...))
}

type CMSServiceExt struct {
	CMSServiceExtHandler
}

func (h *CMSServiceExt) UserLogin(ctx context.Context, in *UserLoginReq, out *UserLoginRsp) error {
	return h.CMSServiceExtHandler.UserLogin(ctx, in, out)
}

func init() { proto.RegisterFile("cms.ext.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x2d, 0xd6,
	0x4b, 0xad, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xe2, 0xe3,
	0xe2, 0x09, 0x2d, 0x4e, 0x2d, 0xf2, 0xc9, 0x4f, 0xcf, 0xcc, 0x0b, 0x4a, 0x2d, 0x44, 0xe5, 0x17,
	0x17, 0x18, 0x39, 0x71, 0xf1, 0x3a, 0xfb, 0x06, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0xba,
	0x56, 0x94, 0x08, 0x19, 0x72, 0x71, 0xc2, 0x15, 0x08, 0x09, 0xe8, 0x15, 0x24, 0xe9, 0x21, 0xeb,
	0x97, 0x42, 0x13, 0x29, 0x2e, 0x50, 0x62, 0x48, 0x62, 0x03, 0x5b, 0x67, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x22, 0x24, 0x7f, 0x82, 0x7f, 0x00, 0x00, 0x00,
}
