// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment.ext.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	comment.ext.proto
	film.ext.proto
	order.ext.proto
	place.ext.proto
	user.ext.proto

It has these top-level messages:
	HotCommentReq
	HotCommentRsp
	CommentData
	CommentMini
	CommentPlus
	CommentRecord
	MakeCommentReq
	MakeCommentRsp
	HotPlayMoviesReq
	HotPlayMoviesRep
	Movie
	HotMovie
	FilmAllMessage
	MovieDetailReq
	MovieDetailRep
	Release
	MovieCreditsWithTypesReq
	MovieCreditsWithTypesRep
	Type
	Persons
	ImageAllReq
	ImageAllRep
	Image
	LocationMoviesReq
	LocationMoviesRep
	MovieComingNewReq
	MovieComingNewRep
	SearchRep
	SearchReq
	SearchMovie
	Genres
	Rating
	Images
	WantTicketReq
	WantTicketRsp
	TicketReq
	TicketRsp
	Order
	LookOrdersReq
	LookOrdersRsp
	PayOrderReq
	PayOrderRsp
	UndoOrderReq
	UndoOrderRsp
	HotCitiesByCinemaReq
	HotCitiesByCinemaRep
	Place
	RegistAccountReq
	RegistAccountRsp
	LoginAccountReq
	LoginAccountRsp
	ResetAccountReq
	ResetAccountRsp
	WantScoreReq
	WantScoreRsp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HotCommentReq struct {
	MovieId int64 `protobuf:"varint,2,opt,name=movieId" json:"movieId,omitempty"`
}

func (m *HotCommentReq) Reset()                    { *m = HotCommentReq{} }
func (m *HotCommentReq) String() string            { return proto.CompactTextString(m) }
func (*HotCommentReq) ProtoMessage()               {}
func (*HotCommentReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HotCommentReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type HotCommentRsp struct {
	Data *CommentData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *HotCommentRsp) Reset()                    { *m = HotCommentRsp{} }
func (m *HotCommentRsp) String() string            { return proto.CompactTextString(m) }
func (*HotCommentRsp) ProtoMessage()               {}
func (*HotCommentRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HotCommentRsp) GetData() *CommentData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommentData struct {
	Mini *CommentMini `protobuf:"bytes,1,opt,name=mini" json:"mini,omitempty"`
	Plus *CommentPlus `protobuf:"bytes,2,opt,name=plus" json:"plus,omitempty"`
}

func (m *CommentData) Reset()                    { *m = CommentData{} }
func (m *CommentData) String() string            { return proto.CompactTextString(m) }
func (*CommentData) ProtoMessage()               {}
func (*CommentData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommentData) GetMini() *CommentMini {
	if m != nil {
		return m.Mini
	}
	return nil
}

func (m *CommentData) GetPlus() *CommentPlus {
	if m != nil {
		return m.Plus
	}
	return nil
}

type CommentMini struct {
	List  []*CommentRecord `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Total int64            `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *CommentMini) Reset()                    { *m = CommentMini{} }
func (m *CommentMini) String() string            { return proto.CompactTextString(m) }
func (*CommentMini) ProtoMessage()               {}
func (*CommentMini) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommentMini) GetList() []*CommentRecord {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CommentMini) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CommentPlus struct {
	List  []*CommentRecord `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Total int64            `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *CommentPlus) Reset()                    { *m = CommentPlus{} }
func (m *CommentPlus) String() string            { return proto.CompactTextString(m) }
func (*CommentPlus) ProtoMessage()               {}
func (*CommentPlus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CommentPlus) GetList() []*CommentRecord {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CommentPlus) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CommentRecord struct {
	Title    string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	HeadImg  string `protobuf:"bytes,3,opt,name=headImg" json:"headImg,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *CommentRecord) Reset()                    { *m = CommentRecord{} }
func (m *CommentRecord) String() string            { return proto.CompactTextString(m) }
func (*CommentRecord) ProtoMessage()               {}
func (*CommentRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommentRecord) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CommentRecord) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommentRecord) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *CommentRecord) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type MakeCommentReq struct {
	MovieId  int64  `protobuf:"varint,1,opt,name=movieId" json:"movieId,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	HeadImg  string `protobuf:"bytes,3,opt,name=headImg" json:"headImg,omitempty"`
	Nickname string `protobuf:"bytes,4,opt,name=nickname" json:"nickname,omitempty"`
	UserId   int64  `protobuf:"varint,5,opt,name=userId" json:"userId,omitempty"`
	Content  string `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
}

func (m *MakeCommentReq) Reset()                    { *m = MakeCommentReq{} }
func (m *MakeCommentReq) String() string            { return proto.CompactTextString(m) }
func (*MakeCommentReq) ProtoMessage()               {}
func (*MakeCommentReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MakeCommentReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *MakeCommentReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MakeCommentReq) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *MakeCommentReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *MakeCommentReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MakeCommentReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MakeCommentRsp struct {
}

func (m *MakeCommentRsp) Reset()                    { *m = MakeCommentRsp{} }
func (m *MakeCommentRsp) String() string            { return proto.CompactTextString(m) }
func (*MakeCommentRsp) ProtoMessage()               {}
func (*MakeCommentRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*HotCommentReq)(nil), "pb.HotCommentReq")
	proto.RegisterType((*HotCommentRsp)(nil), "pb.HotCommentRsp")
	proto.RegisterType((*CommentData)(nil), "pb.CommentData")
	proto.RegisterType((*CommentMini)(nil), "pb.CommentMini")
	proto.RegisterType((*CommentPlus)(nil), "pb.CommentPlus")
	proto.RegisterType((*CommentRecord)(nil), "pb.CommentRecord")
	proto.RegisterType((*MakeCommentReq)(nil), "pb.MakeCommentReq")
	proto.RegisterType((*MakeCommentRsp)(nil), "pb.MakeCommentRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CommentServiceExt service

type CommentServiceExtClient interface {
	// 精彩影评
	HotComment(ctx context.Context, in *HotCommentReq, opts ...client.CallOption) (*HotCommentRsp, error)
	// 进行评论
	MakeComment(ctx context.Context, in *MakeCommentReq, opts ...client.CallOption) (*MakeCommentRsp, error)
}

type commentServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewCommentServiceExtClient(serviceName string, c client.Client) CommentServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &commentServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *commentServiceExtClient) HotComment(ctx context.Context, in *HotCommentReq, opts ...client.CallOption) (*HotCommentRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CommentServiceExt.HotComment", in)
	out := new(HotCommentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceExtClient) MakeComment(ctx context.Context, in *MakeCommentReq, opts ...client.CallOption) (*MakeCommentRsp, error) {
	req := c.c.NewRequest(c.serviceName, "CommentServiceExt.MakeComment", in)
	out := new(MakeCommentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommentServiceExt service

type CommentServiceExtHandler interface {
	// 精彩影评
	HotComment(context.Context, *HotCommentReq, *HotCommentRsp) error
	// 进行评论
	MakeComment(context.Context, *MakeCommentReq, *MakeCommentRsp) error
}

func RegisterCommentServiceExtHandler(s server.Server, hdlr CommentServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CommentServiceExt{hdlr}, opts...))
}

type CommentServiceExt struct {
	CommentServiceExtHandler
}

func (h *CommentServiceExt) HotComment(ctx context.Context, in *HotCommentReq, out *HotCommentRsp) error {
	return h.CommentServiceExtHandler.HotComment(ctx, in, out)
}

func (h *CommentServiceExt) MakeComment(ctx context.Context, in *MakeCommentReq, out *MakeCommentRsp) error {
	return h.CommentServiceExtHandler.MakeComment(ctx, in, out)
}

func init() { proto.RegisterFile("comment.ext.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x4b, 0x2b, 0x31,
	0x14, 0x7d, 0xd3, 0xaf, 0xf7, 0x7a, 0x87, 0x3e, 0x6d, 0x10, 0x19, 0xba, 0x2a, 0x11, 0xa1, 0x6e,
	0x66, 0x51, 0x0b, 0xfe, 0x00, 0x15, 0xac, 0x50, 0x90, 0xb8, 0x70, 0x9d, 0xce, 0x04, 0x0d, 0x9d,
	0x49, 0xe2, 0x24, 0x53, 0xba, 0xf6, 0xd7, 0xf8, 0x33, 0x25, 0x99, 0x69, 0x3b, 0xa9, 0xdd, 0x88,
	0xcb, 0x73, 0xcf, 0x39, 0xf7, 0x23, 0xf7, 0x06, 0x86, 0x89, 0xcc, 0x73, 0x26, 0x4c, 0xcc, 0x36,
	0x26, 0x56, 0x85, 0x34, 0x12, 0xb5, 0xd4, 0x12, 0x5f, 0xc1, 0xe0, 0x41, 0x9a, 0xdb, 0x8a, 0x23,
	0xec, 0x1d, 0x45, 0xf0, 0x37, 0x97, 0x6b, 0xce, 0xe6, 0x69, 0xd4, 0x1a, 0x07, 0x93, 0x36, 0xd9,
	0x42, 0x3c, 0xf3, 0xa4, 0x5a, 0xa1, 0x0b, 0xe8, 0xa4, 0xd4, 0xd0, 0x28, 0x18, 0x07, 0x93, 0x70,
	0x7a, 0x12, 0xab, 0x65, 0x5c, 0xb3, 0x77, 0xd4, 0x50, 0xe2, 0x48, 0xfc, 0x02, 0x61, 0x23, 0x68,
	0x3d, 0x39, 0x17, 0xfc, 0x88, 0x67, 0xc1, 0x05, 0x27, 0x8e, 0xb4, 0x22, 0x95, 0x95, 0xda, 0x35,
	0xe0, 0x8b, 0x9e, 0xb2, 0x52, 0x13, 0x47, 0xe2, 0xc7, 0x5d, 0x62, 0xeb, 0x44, 0x97, 0xd0, 0xc9,
	0xb8, 0x36, 0x51, 0x30, 0x6e, 0x4f, 0xc2, 0xe9, 0xb0, 0xe1, 0x21, 0x2c, 0x91, 0x45, 0x4a, 0x1c,
	0x8d, 0xce, 0xa0, 0x6b, 0xa4, 0xa1, 0x59, 0x3d, 0x5c, 0x05, 0x1a, 0xb9, 0x6c, 0x81, 0xdf, 0xe5,
	0x2a, 0x61, 0xe0, 0x89, 0x9d, 0x8c, 0x9b, 0x8c, 0xb9, 0x99, 0xfb, 0xa4, 0x02, 0xf6, 0x9d, 0x13,
	0x29, 0x0c, 0x13, 0xc6, 0xd9, 0xfb, 0x64, 0x0b, 0x2d, 0xf3, 0xc6, 0x68, 0x3a, 0xcf, 0x5f, 0xa3,
	0x76, 0xc5, 0xd4, 0x10, 0x8d, 0xe0, 0x9f, 0xe0, 0xc9, 0x4a, 0xd0, 0x9c, 0x45, 0x1d, 0x47, 0xed,
	0x30, 0xfe, 0x0c, 0xe0, 0xff, 0x82, 0xae, 0xd8, 0xf1, 0x55, 0x06, 0xde, 0x2a, 0xf7, 0x2d, 0xb5,
	0x0e, 0x5a, 0xfa, 0x79, 0x61, 0x74, 0x0e, 0xbd, 0x52, 0xb3, 0x62, 0x9e, 0x46, 0x5d, 0x57, 0xa4,
	0x46, 0xcd, 0x01, 0x7b, 0xde, 0x80, 0xf8, 0xd4, 0xef, 0x54, 0xab, 0xe9, 0x47, 0x00, 0xc3, 0x1a,
	0x3e, 0xb3, 0x62, 0xcd, 0x13, 0x76, 0xbf, 0x31, 0x68, 0x06, 0xb0, 0x3f, 0x38, 0xe4, 0xd6, 0xe0,
	0xdd, 0xea, 0xe8, 0x30, 0xa4, 0x15, 0xfe, 0x83, 0x6e, 0x20, 0x6c, 0x64, 0x47, 0xc8, 0x6a, 0xfc,
	0x87, 0x19, 0x7d, 0x8b, 0x59, 0xe3, 0xb2, 0xe7, 0x7e, 0xc5, 0xf5, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x93, 0xf5, 0xb4, 0x9d, 0x2a, 0x03, 0x00, 0x00,
}
