// Code generated by protoc-gen-go. DO NOT EDIT.
// source: film.ext.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HotPlayMoviesReq struct {
	Location int64 `protobuf:"varint,1,opt,name=location" json:"location,omitempty"`
}

func (m *HotPlayMoviesReq) Reset()                    { *m = HotPlayMoviesReq{} }
func (m *HotPlayMoviesReq) String() string            { return proto.CompactTextString(m) }
func (*HotPlayMoviesReq) ProtoMessage()               {}
func (*HotPlayMoviesReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *HotPlayMoviesReq) GetLocation() int64 {
	if m != nil {
		return m.Location
	}
	return 0
}

type HotPlayMoviesRep struct {
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *HotPlayMoviesRep) Reset()                    { *m = HotPlayMoviesRep{} }
func (m *HotPlayMoviesRep) String() string            { return proto.CompactTextString(m) }
func (*HotPlayMoviesRep) ProtoMessage()               {}
func (*HotPlayMoviesRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *HotPlayMoviesRep) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type Movie struct {
	Img              string   `protobuf:"bytes,1,opt,name=img" json:"img,omitempty"`
	MovieId          int64    `protobuf:"varint,2,opt,name=movieId" json:"movieId,omitempty"`
	TitleCn          string   `protobuf:"bytes,3,opt,name=titleCn" json:"titleCn,omitempty"`
	MovieSupportType string   `protobuf:"bytes,4,opt,name=movieSupportType" json:"movieSupportType,omitempty"`
	FilmDirector     string   `protobuf:"bytes,5,opt,name=filmDirector" json:"filmDirector,omitempty"`
	Actors           []string `protobuf:"bytes,6,rep,name=actors" json:"actors,omitempty"`
	FilmDrama        string   `protobuf:"bytes,7,opt,name=filmDrama" json:"filmDrama,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Movie) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *Movie) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *Movie) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *Movie) GetMovieSupportType() string {
	if m != nil {
		return m.MovieSupportType
	}
	return ""
}

func (m *Movie) GetFilmDirector() string {
	if m != nil {
		return m.FilmDirector
	}
	return ""
}

func (m *Movie) GetActors() []string {
	if m != nil {
		return m.Actors
	}
	return nil
}

func (m *Movie) GetFilmDrama() string {
	if m != nil {
		return m.FilmDrama
	}
	return ""
}

type HotMovie struct {
	ActorName     []string `protobuf:"bytes,1,rep,name=actorName" json:"actorName,omitempty"`
	CommonSpecial string   `protobuf:"bytes,2,opt,name=commonSpecial" json:"commonSpecial,omitempty"`
	DirectorName  string   `protobuf:"bytes,3,opt,name=directorName" json:"directorName,omitempty"`
	Img           string   `protobuf:"bytes,4,opt,name=img" json:"img,omitempty"`
	Is3D          int64    `protobuf:"varint,5,opt,name=is3D" json:"is3D,omitempty"`
	IsDMAX        int64    `protobuf:"varint,6,opt,name=isDMAX" json:"isDMAX,omitempty"`
	IsFilter      int64    `protobuf:"varint,7,opt,name=isFilter" json:"isFilter,omitempty"`
	IsHot         int64    `protobuf:"varint,8,opt,name=isHot" json:"isHot,omitempty"`
	IsIMAX        int64    `protobuf:"varint,9,opt,name=isIMAX" json:"isIMAX,omitempty"`
	IsIMAX3D      int64    `protobuf:"varint,10,opt,name=isIMAX3D" json:"isIMAX3D,omitempty"`
	IsNew         int64    `protobuf:"varint,11,opt,name=isNew" json:"isNew,omitempty"`
	Length        int64    `protobuf:"varint,12,opt,name=length" json:"length,omitempty"`
	MovieId       int64    `protobuf:"varint,13,opt,name=movieId" json:"movieId,omitempty"`
	RDay          int64    `protobuf:"varint,14,opt,name=rDay" json:"rDay,omitempty"`
	RMonth        int64    `protobuf:"varint,15,opt,name=rMonth" json:"rMonth,omitempty"`
	RYear         int64    `protobuf:"varint,16,opt,name=rYear" json:"rYear,omitempty"`
	RatingFinal   float32  `protobuf:"fixed32,17,opt,name=ratingFinal" json:"ratingFinal,omitempty"`
	T             string   `protobuf:"bytes,18,opt,name=t" json:"t,omitempty"`
	TitleCn       string   `protobuf:"bytes,19,opt,name=titleCn" json:"titleCn,omitempty"`
	TitleEn       string   `protobuf:"bytes,20,opt,name=titleEn" json:"titleEn,omitempty"`
	Type          string   `protobuf:"bytes,21,opt,name=type" json:"type,omitempty"`
	WantedCount   int64    `protobuf:"varint,22,opt,name=wantedCount" json:"wantedCount,omitempty"`
}

func (m *HotMovie) Reset()                    { *m = HotMovie{} }
func (m *HotMovie) String() string            { return proto.CompactTextString(m) }
func (*HotMovie) ProtoMessage()               {}
func (*HotMovie) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *HotMovie) GetActorName() []string {
	if m != nil {
		return m.ActorName
	}
	return nil
}

func (m *HotMovie) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

func (m *HotMovie) GetDirectorName() string {
	if m != nil {
		return m.DirectorName
	}
	return ""
}

func (m *HotMovie) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *HotMovie) GetIs3D() int64 {
	if m != nil {
		return m.Is3D
	}
	return 0
}

func (m *HotMovie) GetIsDMAX() int64 {
	if m != nil {
		return m.IsDMAX
	}
	return 0
}

func (m *HotMovie) GetIsFilter() int64 {
	if m != nil {
		return m.IsFilter
	}
	return 0
}

func (m *HotMovie) GetIsHot() int64 {
	if m != nil {
		return m.IsHot
	}
	return 0
}

func (m *HotMovie) GetIsIMAX() int64 {
	if m != nil {
		return m.IsIMAX
	}
	return 0
}

func (m *HotMovie) GetIsIMAX3D() int64 {
	if m != nil {
		return m.IsIMAX3D
	}
	return 0
}

func (m *HotMovie) GetIsNew() int64 {
	if m != nil {
		return m.IsNew
	}
	return 0
}

func (m *HotMovie) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *HotMovie) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *HotMovie) GetRDay() int64 {
	if m != nil {
		return m.RDay
	}
	return 0
}

func (m *HotMovie) GetRMonth() int64 {
	if m != nil {
		return m.RMonth
	}
	return 0
}

func (m *HotMovie) GetRYear() int64 {
	if m != nil {
		return m.RYear
	}
	return 0
}

func (m *HotMovie) GetRatingFinal() float32 {
	if m != nil {
		return m.RatingFinal
	}
	return 0
}

func (m *HotMovie) GetT() string {
	if m != nil {
		return m.T
	}
	return ""
}

func (m *HotMovie) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *HotMovie) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *HotMovie) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HotMovie) GetWantedCount() int64 {
	if m != nil {
		return m.WantedCount
	}
	return 0
}

type FilmAllMessage struct {
	Logo                 string  `protobuf:"bytes,1,opt,name=logo" json:"logo,omitempty"`
	FilmLong             int64   `protobuf:"varint,2,opt,name=filmLong" json:"filmLong,omitempty"`
	IsSelectSeat         int64   `protobuf:"varint,3,opt,name=isSelectSeat" json:"isSelectSeat,omitempty"`
	FilmPrice            float32 `protobuf:"fixed32,4,opt,name=filmPrice" json:"filmPrice,omitempty"`
	FilmScreenwriter     string  `protobuf:"bytes,5,opt,name=filmScreenwriter" json:"filmScreenwriter,omitempty"`
	CommentNum           int64   `protobuf:"varint,6,opt,name=commentNum" json:"commentNum,omitempty"`
	FilmName             string  `protobuf:"bytes,7,opt,name=filmName" json:"filmName,omitempty"`
	IsSupportInlineWatch int64   `protobuf:"varint,8,opt,name=isSupportInlineWatch" json:"isSupportInlineWatch,omitempty"`
	CreateAt             string  `protobuf:"bytes,9,opt,name=createAt" json:"createAt,omitempty"`
	BigType              int64   `protobuf:"varint,10,opt,name=bigType" json:"bigType,omitempty"`
	FilmDrama            string  `protobuf:"bytes,11,opt,name=filmDrama" json:"filmDrama,omitempty"`
	UserAccessTimes      int64   `protobuf:"varint,12,opt,name=userAccessTimes" json:"userAccessTimes,omitempty"`
	FilmBoxoffice        float32 `protobuf:"fixed32,13,opt,name=filmBoxoffice" json:"filmBoxoffice,omitempty"`
	FilmDirector         string  `protobuf:"bytes,14,opt,name=filmDirector" json:"filmDirector,omitempty"`
	UserLikeWatchTimes   int64   `protobuf:"varint,15,opt,name=userLikeWatchTimes" json:"userLikeWatchTimes,omitempty"`
	UserCommentTimes     int64   `protobuf:"varint,16,opt,name=userCommentTimes" json:"userCommentTimes,omitempty"`
	CompanyIssued        string  `protobuf:"bytes,17,opt,name=companyIssued" json:"companyIssued,omitempty"`
	Country              string  `protobuf:"bytes,18,opt,name=country" json:"country,omitempty"`
	CommentScore         float32 `protobuf:"fixed32,19,opt,name=commentScore" json:"commentScore,omitempty"`
	Is3D                 int64   `protobuf:"varint,20,opt,name=is3D" json:"is3D,omitempty"`
	IsDMAX               int64   `protobuf:"varint,21,opt,name=isDMAX" json:"isDMAX,omitempty"`
	IsFilter             int64   `protobuf:"varint,22,opt,name=isFilter" json:"isFilter,omitempty"`
	IsHot                int64   `protobuf:"varint,23,opt,name=isHot" json:"isHot,omitempty"`
	IsIMAX               int64   `protobuf:"varint,24,opt,name=isIMAX" json:"isIMAX,omitempty"`
	IsIMAX3D             int64   `protobuf:"varint,25,opt,name=isIMAX3D" json:"isIMAX3D,omitempty"`
	IsNew                int64   `protobuf:"varint,26,opt,name=isNew" json:"isNew,omitempty"`
	RDay                 int64   `protobuf:"varint,27,opt,name=rDay" json:"rDay,omitempty"`
	RMonth               int64   `protobuf:"varint,28,opt,name=rMonth" json:"rMonth,omitempty"`
	RYear                int64   `protobuf:"varint,29,opt,name=rYear" json:"rYear,omitempty"`
	CommonSpecial        string  `protobuf:"bytes,30,opt,name=commonSpecial" json:"commonSpecial,omitempty"`
}

func (m *FilmAllMessage) Reset()                    { *m = FilmAllMessage{} }
func (m *FilmAllMessage) String() string            { return proto.CompactTextString(m) }
func (*FilmAllMessage) ProtoMessage()               {}
func (*FilmAllMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *FilmAllMessage) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *FilmAllMessage) GetFilmLong() int64 {
	if m != nil {
		return m.FilmLong
	}
	return 0
}

func (m *FilmAllMessage) GetIsSelectSeat() int64 {
	if m != nil {
		return m.IsSelectSeat
	}
	return 0
}

func (m *FilmAllMessage) GetFilmPrice() float32 {
	if m != nil {
		return m.FilmPrice
	}
	return 0
}

func (m *FilmAllMessage) GetFilmScreenwriter() string {
	if m != nil {
		return m.FilmScreenwriter
	}
	return ""
}

func (m *FilmAllMessage) GetCommentNum() int64 {
	if m != nil {
		return m.CommentNum
	}
	return 0
}

func (m *FilmAllMessage) GetFilmName() string {
	if m != nil {
		return m.FilmName
	}
	return ""
}

func (m *FilmAllMessage) GetIsSupportInlineWatch() int64 {
	if m != nil {
		return m.IsSupportInlineWatch
	}
	return 0
}

func (m *FilmAllMessage) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *FilmAllMessage) GetBigType() int64 {
	if m != nil {
		return m.BigType
	}
	return 0
}

func (m *FilmAllMessage) GetFilmDrama() string {
	if m != nil {
		return m.FilmDrama
	}
	return ""
}

func (m *FilmAllMessage) GetUserAccessTimes() int64 {
	if m != nil {
		return m.UserAccessTimes
	}
	return 0
}

func (m *FilmAllMessage) GetFilmBoxoffice() float32 {
	if m != nil {
		return m.FilmBoxoffice
	}
	return 0
}

func (m *FilmAllMessage) GetFilmDirector() string {
	if m != nil {
		return m.FilmDirector
	}
	return ""
}

func (m *FilmAllMessage) GetUserLikeWatchTimes() int64 {
	if m != nil {
		return m.UserLikeWatchTimes
	}
	return 0
}

func (m *FilmAllMessage) GetUserCommentTimes() int64 {
	if m != nil {
		return m.UserCommentTimes
	}
	return 0
}

func (m *FilmAllMessage) GetCompanyIssued() string {
	if m != nil {
		return m.CompanyIssued
	}
	return ""
}

func (m *FilmAllMessage) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *FilmAllMessage) GetCommentScore() float32 {
	if m != nil {
		return m.CommentScore
	}
	return 0
}

func (m *FilmAllMessage) GetIs3D() int64 {
	if m != nil {
		return m.Is3D
	}
	return 0
}

func (m *FilmAllMessage) GetIsDMAX() int64 {
	if m != nil {
		return m.IsDMAX
	}
	return 0
}

func (m *FilmAllMessage) GetIsFilter() int64 {
	if m != nil {
		return m.IsFilter
	}
	return 0
}

func (m *FilmAllMessage) GetIsHot() int64 {
	if m != nil {
		return m.IsHot
	}
	return 0
}

func (m *FilmAllMessage) GetIsIMAX() int64 {
	if m != nil {
		return m.IsIMAX
	}
	return 0
}

func (m *FilmAllMessage) GetIsIMAX3D() int64 {
	if m != nil {
		return m.IsIMAX3D
	}
	return 0
}

func (m *FilmAllMessage) GetIsNew() int64 {
	if m != nil {
		return m.IsNew
	}
	return 0
}

func (m *FilmAllMessage) GetRDay() int64 {
	if m != nil {
		return m.RDay
	}
	return 0
}

func (m *FilmAllMessage) GetRMonth() int64 {
	if m != nil {
		return m.RMonth
	}
	return 0
}

func (m *FilmAllMessage) GetRYear() int64 {
	if m != nil {
		return m.RYear
	}
	return 0
}

func (m *FilmAllMessage) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

type MovieDetailReq struct {
	LocationId int64 `protobuf:"varint,1,opt,name=locationId" json:"locationId,omitempty"`
	MovieId    int64 `protobuf:"varint,2,opt,name=movieId" json:"movieId,omitempty"`
}

func (m *MovieDetailReq) Reset()                    { *m = MovieDetailReq{} }
func (m *MovieDetailReq) String() string            { return proto.CompactTextString(m) }
func (*MovieDetailReq) ProtoMessage()               {}
func (*MovieDetailReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *MovieDetailReq) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *MovieDetailReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type MovieDetailRep struct {
	Image         string   `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	TitleCn       string   `protobuf:"bytes,2,opt,name=titleCn" json:"titleCn,omitempty"`
	TitleEn       string   `protobuf:"bytes,3,opt,name=titleEn" json:"titleEn,omitempty"`
	Rating        float32  `protobuf:"fixed32,4,opt,name=rating" json:"rating,omitempty"`
	Year          int64    `protobuf:"varint,5,opt,name=year" json:"year,omitempty"`
	Content       string   `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	Type          []string `protobuf:"bytes,7,rep,name=type" json:"type,omitempty"`
	RunTime       int64    `protobuf:"varint,8,opt,name=runTime" json:"runTime,omitempty"`
	CommonSpecial string   `protobuf:"bytes,9,opt,name=commonSpecial" json:"commonSpecial,omitempty"`
	Director      string   `protobuf:"bytes,10,opt,name=director" json:"director,omitempty"`
	Release       *Release `protobuf:"bytes,11,opt,name=release" json:"release,omitempty"`
}

func (m *MovieDetailRep) Reset()                    { *m = MovieDetailRep{} }
func (m *MovieDetailRep) String() string            { return proto.CompactTextString(m) }
func (*MovieDetailRep) ProtoMessage()               {}
func (*MovieDetailRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *MovieDetailRep) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *MovieDetailRep) GetTitleCn() string {
	if m != nil {
		return m.TitleCn
	}
	return ""
}

func (m *MovieDetailRep) GetTitleEn() string {
	if m != nil {
		return m.TitleEn
	}
	return ""
}

func (m *MovieDetailRep) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *MovieDetailRep) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *MovieDetailRep) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MovieDetailRep) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *MovieDetailRep) GetRunTime() int64 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *MovieDetailRep) GetCommonSpecial() string {
	if m != nil {
		return m.CommonSpecial
	}
	return ""
}

func (m *MovieDetailRep) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *MovieDetailRep) GetRelease() *Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type Release struct {
	Location string `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Date     string `protobuf:"bytes,2,opt,name=date" json:"date,omitempty"`
}

func (m *Release) Reset()                    { *m = Release{} }
func (m *Release) String() string            { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()               {}
func (*Release) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *Release) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Release) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type MovieCreditsWithTypesReq struct {
	MovieId int64 `protobuf:"varint,1,opt,name=MovieId" json:"MovieId,omitempty"`
}

func (m *MovieCreditsWithTypesReq) Reset()                    { *m = MovieCreditsWithTypesReq{} }
func (m *MovieCreditsWithTypesReq) String() string            { return proto.CompactTextString(m) }
func (*MovieCreditsWithTypesReq) ProtoMessage()               {}
func (*MovieCreditsWithTypesReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *MovieCreditsWithTypesReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type MovieCreditsWithTypesRep struct {
	Types []*Type `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
}

func (m *MovieCreditsWithTypesRep) Reset()                    { *m = MovieCreditsWithTypesRep{} }
func (m *MovieCreditsWithTypesRep) String() string            { return proto.CompactTextString(m) }
func (*MovieCreditsWithTypesRep) ProtoMessage()               {}
func (*MovieCreditsWithTypesRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *MovieCreditsWithTypesRep) GetTypes() []*Type {
	if m != nil {
		return m.Types
	}
	return nil
}

type Type struct {
	TypeName   string     `protobuf:"bytes,1,opt,name=typeName" json:"typeName,omitempty"`
	TypeNameEc string     `protobuf:"bytes,2,opt,name=typeNameEc" json:"typeNameEc,omitempty"`
	Persons    []*Persons `protobuf:"bytes,3,rep,name=persons" json:"persons,omitempty"`
}

func (m *Type) Reset()                    { *m = Type{} }
func (m *Type) String() string            { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()               {}
func (*Type) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *Type) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Type) GetTypeNameEc() string {
	if m != nil {
		return m.TypeNameEc
	}
	return ""
}

func (m *Type) GetPersons() []*Persons {
	if m != nil {
		return m.Persons
	}
	return nil
}

type Persons struct {
	Image     string `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NameEn    string `protobuf:"bytes,3,opt,name=nameEn" json:"nameEn,omitempty"`
	RoleCover string `protobuf:"bytes,4,opt,name=roleCover" json:"roleCover,omitempty"`
	Personate string `protobuf:"bytes,5,opt,name=personate" json:"personate,omitempty"`
}

func (m *Persons) Reset()                    { *m = Persons{} }
func (m *Persons) String() string            { return proto.CompactTextString(m) }
func (*Persons) ProtoMessage()               {}
func (*Persons) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *Persons) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Persons) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Persons) GetNameEn() string {
	if m != nil {
		return m.NameEn
	}
	return ""
}

func (m *Persons) GetRoleCover() string {
	if m != nil {
		return m.RoleCover
	}
	return ""
}

func (m *Persons) GetPersonate() string {
	if m != nil {
		return m.Personate
	}
	return ""
}

type ImageAllReq struct {
	MovieId int64 `protobuf:"varint,2,opt,name=movieId" json:"movieId,omitempty"`
}

func (m *ImageAllReq) Reset()                    { *m = ImageAllReq{} }
func (m *ImageAllReq) String() string            { return proto.CompactTextString(m) }
func (*ImageAllReq) ProtoMessage()               {}
func (*ImageAllReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *ImageAllReq) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type ImageAllRep struct {
	Images []*Image `protobuf:"bytes,1,rep,name=images" json:"images,omitempty"`
}

func (m *ImageAllRep) Reset()                    { *m = ImageAllRep{} }
func (m *ImageAllRep) String() string            { return proto.CompactTextString(m) }
func (*ImageAllRep) ProtoMessage()               {}
func (*ImageAllRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *ImageAllRep) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Image struct {
	Image string `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *Image) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type LocationMoviesReq struct {
}

func (m *LocationMoviesReq) Reset()                    { *m = LocationMoviesReq{} }
func (m *LocationMoviesReq) String() string            { return proto.CompactTextString(m) }
func (*LocationMoviesReq) ProtoMessage()               {}
func (*LocationMoviesReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

type LocationMoviesRep struct {
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *LocationMoviesRep) Reset()                    { *m = LocationMoviesRep{} }
func (m *LocationMoviesRep) String() string            { return proto.CompactTextString(m) }
func (*LocationMoviesRep) ProtoMessage()               {}
func (*LocationMoviesRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *LocationMoviesRep) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type MovieComingNewReq struct {
}

func (m *MovieComingNewReq) Reset()                    { *m = MovieComingNewReq{} }
func (m *MovieComingNewReq) String() string            { return proto.CompactTextString(m) }
func (*MovieComingNewReq) ProtoMessage()               {}
func (*MovieComingNewReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

type MovieComingNewRep struct {
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *MovieComingNewRep) Reset()                    { *m = MovieComingNewRep{} }
func (m *MovieComingNewRep) String() string            { return proto.CompactTextString(m) }
func (*MovieComingNewRep) ProtoMessage()               {}
func (*MovieComingNewRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *MovieComingNewRep) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type SearchRep struct {
	Subjects []*SearchMovie `protobuf:"bytes,1,rep,name=subjects" json:"subjects,omitempty"`
	Total    int64          `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (m *SearchRep) Reset()                    { *m = SearchRep{} }
func (m *SearchRep) String() string            { return proto.CompactTextString(m) }
func (*SearchRep) ProtoMessage()               {}
func (*SearchRep) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *SearchRep) GetSubjects() []*SearchMovie {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *SearchRep) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type SearchReq struct {
	Q string `protobuf:"bytes,1,opt,name=q" json:"q,omitempty"`
}

func (m *SearchReq) Reset()                    { *m = SearchReq{} }
func (m *SearchReq) String() string            { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()               {}
func (*SearchReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

func (m *SearchReq) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type SearchMovie struct {
	Title  string    `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Id     string    `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Image  *Images   `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Genres []*Genres `protobuf:"bytes,4,rep,name=genres" json:"genres,omitempty"`
	Year   string    `protobuf:"bytes,5,opt,name=year" json:"year,omitempty"`
	Rating *Rating   `protobuf:"bytes,6,opt,name=rating" json:"rating,omitempty"`
}

func (m *SearchMovie) Reset()                    { *m = SearchMovie{} }
func (m *SearchMovie) String() string            { return proto.CompactTextString(m) }
func (*SearchMovie) ProtoMessage()               {}
func (*SearchMovie) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{21} }

func (m *SearchMovie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchMovie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchMovie) GetImage() *Images {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *SearchMovie) GetGenres() []*Genres {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *SearchMovie) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *SearchMovie) GetRating() *Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type Genres struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *Genres) Reset()                    { *m = Genres{} }
func (m *Genres) String() string            { return proto.CompactTextString(m) }
func (*Genres) ProtoMessage()               {}
func (*Genres) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{22} }

func (m *Genres) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Rating struct {
	Average float32 `protobuf:"fixed32,1,opt,name=average" json:"average,omitempty"`
}

func (m *Rating) Reset()                    { *m = Rating{} }
func (m *Rating) String() string            { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()               {}
func (*Rating) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{23} }

func (m *Rating) GetAverage() float32 {
	if m != nil {
		return m.Average
	}
	return 0
}

type Images struct {
	Small string `protobuf:"bytes,1,opt,name=small" json:"small,omitempty"`
}

func (m *Images) Reset()                    { *m = Images{} }
func (m *Images) String() string            { return proto.CompactTextString(m) }
func (*Images) ProtoMessage()               {}
func (*Images) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{24} }

func (m *Images) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

type GetFilmsByCidReq struct {
	CinemaId int64 `protobuf:"varint,1,opt,name=cinemaId" json:"cinemaId,omitempty"`
}

func (m *GetFilmsByCidReq) Reset()                    { *m = GetFilmsByCidReq{} }
func (m *GetFilmsByCidReq) String() string            { return proto.CompactTextString(m) }
func (*GetFilmsByCidReq) ProtoMessage()               {}
func (*GetFilmsByCidReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{25} }

func (m *GetFilmsByCidReq) GetCinemaId() int64 {
	if m != nil {
		return m.CinemaId
	}
	return 0
}

type GetFilmsByCidRsp struct {
	Movies []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *GetFilmsByCidRsp) Reset()                    { *m = GetFilmsByCidRsp{} }
func (m *GetFilmsByCidRsp) String() string            { return proto.CompactTextString(m) }
func (*GetFilmsByCidRsp) ProtoMessage()               {}
func (*GetFilmsByCidRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{26} }

func (m *GetFilmsByCidRsp) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func init() {
	proto.RegisterType((*HotPlayMoviesReq)(nil), "pb.HotPlayMoviesReq")
	proto.RegisterType((*HotPlayMoviesRep)(nil), "pb.HotPlayMoviesRep")
	proto.RegisterType((*Movie)(nil), "pb.Movie")
	proto.RegisterType((*HotMovie)(nil), "pb.HotMovie")
	proto.RegisterType((*FilmAllMessage)(nil), "pb.FilmAllMessage")
	proto.RegisterType((*MovieDetailReq)(nil), "pb.MovieDetailReq")
	proto.RegisterType((*MovieDetailRep)(nil), "pb.MovieDetailRep")
	proto.RegisterType((*Release)(nil), "pb.Release")
	proto.RegisterType((*MovieCreditsWithTypesReq)(nil), "pb.MovieCreditsWithTypesReq")
	proto.RegisterType((*MovieCreditsWithTypesRep)(nil), "pb.MovieCreditsWithTypesRep")
	proto.RegisterType((*Type)(nil), "pb.Type")
	proto.RegisterType((*Persons)(nil), "pb.Persons")
	proto.RegisterType((*ImageAllReq)(nil), "pb.ImageAllReq")
	proto.RegisterType((*ImageAllRep)(nil), "pb.ImageAllRep")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*LocationMoviesReq)(nil), "pb.LocationMoviesReq")
	proto.RegisterType((*LocationMoviesRep)(nil), "pb.LocationMoviesRep")
	proto.RegisterType((*MovieComingNewReq)(nil), "pb.MovieComingNewReq")
	proto.RegisterType((*MovieComingNewRep)(nil), "pb.MovieComingNewRep")
	proto.RegisterType((*SearchRep)(nil), "pb.SearchRep")
	proto.RegisterType((*SearchReq)(nil), "pb.SearchReq")
	proto.RegisterType((*SearchMovie)(nil), "pb.SearchMovie")
	proto.RegisterType((*Genres)(nil), "pb.Genres")
	proto.RegisterType((*Rating)(nil), "pb.Rating")
	proto.RegisterType((*Images)(nil), "pb.Images")
	proto.RegisterType((*GetFilmsByCidReq)(nil), "pb.GetFilmsByCidReq")
	proto.RegisterType((*GetFilmsByCidRsp)(nil), "pb.GetFilmsByCidRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FilmServiceExt service

type FilmServiceExtClient interface {
	// 获取正在售票的影片
	HotPlayMovies(ctx context.Context, in *HotPlayMoviesReq, opts ...client.CallOption) (*HotPlayMoviesRep, error)
	// 电影详情
	MovieDetail(ctx context.Context, in *MovieDetailReq, opts ...client.CallOption) (*MovieDetailRep, error)
	// 获取导演与演员信息
	MovieCreditsWithTypes(ctx context.Context, in *MovieCreditsWithTypesReq, opts ...client.CallOption) (*MovieCreditsWithTypesRep, error)
	// 获取海报信息
	ImageAll(ctx context.Context, in *ImageAllReq, opts ...client.CallOption) (*ImageAllRep, error)
	// 正在热映的影片
	LocationMovies(ctx context.Context, in *LocationMoviesReq, opts ...client.CallOption) (*LocationMoviesRep, error)
	// 即将上映的影片
	MovieComingNew(ctx context.Context, in *MovieComingNewReq, opts ...client.CallOption) (*MovieComingNewRep, error)
	// 图片搜索
	Search(ctx context.Context, in *SearchReq, opts ...client.CallOption) (*SearchRep, error)
}

type filmServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewFilmServiceExtClient(serviceName string, c client.Client) FilmServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &filmServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *filmServiceExtClient) HotPlayMovies(ctx context.Context, in *HotPlayMoviesReq, opts ...client.CallOption) (*HotPlayMoviesRep, error) {
	req := c.c.NewRequest(c.serviceName, "FilmServiceExt.HotPlayMovies", in)
	out := new(HotPlayMoviesRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceExtClient) MovieDetail(ctx context.Context, in *MovieDetailReq, opts ...client.CallOption) (*MovieDetailRep, error) {
	req := c.c.NewRequest(c.serviceName, "FilmServiceExt.MovieDetail", in)
	out := new(MovieDetailRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceExtClient) MovieCreditsWithTypes(ctx context.Context, in *MovieCreditsWithTypesReq, opts ...client.CallOption) (*MovieCreditsWithTypesRep, error) {
	req := c.c.NewRequest(c.serviceName, "FilmServiceExt.MovieCreditsWithTypes", in)
	out := new(MovieCreditsWithTypesRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceExtClient) ImageAll(ctx context.Context, in *ImageAllReq, opts ...client.CallOption) (*ImageAllRep, error) {
	req := c.c.NewRequest(c.serviceName, "FilmServiceExt.ImageAll", in)
	out := new(ImageAllRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceExtClient) LocationMovies(ctx context.Context, in *LocationMoviesReq, opts ...client.CallOption) (*LocationMoviesRep, error) {
	req := c.c.NewRequest(c.serviceName, "FilmServiceExt.LocationMovies", in)
	out := new(LocationMoviesRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceExtClient) MovieComingNew(ctx context.Context, in *MovieComingNewReq, opts ...client.CallOption) (*MovieComingNewRep, error) {
	req := c.c.NewRequest(c.serviceName, "FilmServiceExt.MovieComingNew", in)
	out := new(MovieComingNewRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceExtClient) Search(ctx context.Context, in *SearchReq, opts ...client.CallOption) (*SearchRep, error) {
	req := c.c.NewRequest(c.serviceName, "FilmServiceExt.Search", in)
	out := new(SearchRep)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FilmServiceExt service

type FilmServiceExtHandler interface {
	// 获取正在售票的影片
	HotPlayMovies(context.Context, *HotPlayMoviesReq, *HotPlayMoviesRep) error
	// 电影详情
	MovieDetail(context.Context, *MovieDetailReq, *MovieDetailRep) error
	// 获取导演与演员信息
	MovieCreditsWithTypes(context.Context, *MovieCreditsWithTypesReq, *MovieCreditsWithTypesRep) error
	// 获取海报信息
	ImageAll(context.Context, *ImageAllReq, *ImageAllRep) error
	// 正在热映的影片
	LocationMovies(context.Context, *LocationMoviesReq, *LocationMoviesRep) error
	// 即将上映的影片
	MovieComingNew(context.Context, *MovieComingNewReq, *MovieComingNewRep) error
	// 图片搜索
	Search(context.Context, *SearchReq, *SearchRep) error
}

func RegisterFilmServiceExtHandler(s server.Server, hdlr FilmServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&FilmServiceExt{hdlr}, opts...))
}

type FilmServiceExt struct {
	FilmServiceExtHandler
}

func (h *FilmServiceExt) HotPlayMovies(ctx context.Context, in *HotPlayMoviesReq, out *HotPlayMoviesRep) error {
	return h.FilmServiceExtHandler.HotPlayMovies(ctx, in, out)
}

func (h *FilmServiceExt) MovieDetail(ctx context.Context, in *MovieDetailReq, out *MovieDetailRep) error {
	return h.FilmServiceExtHandler.MovieDetail(ctx, in, out)
}

func (h *FilmServiceExt) MovieCreditsWithTypes(ctx context.Context, in *MovieCreditsWithTypesReq, out *MovieCreditsWithTypesRep) error {
	return h.FilmServiceExtHandler.MovieCreditsWithTypes(ctx, in, out)
}

func (h *FilmServiceExt) ImageAll(ctx context.Context, in *ImageAllReq, out *ImageAllRep) error {
	return h.FilmServiceExtHandler.ImageAll(ctx, in, out)
}

func (h *FilmServiceExt) LocationMovies(ctx context.Context, in *LocationMoviesReq, out *LocationMoviesRep) error {
	return h.FilmServiceExtHandler.LocationMovies(ctx, in, out)
}

func (h *FilmServiceExt) MovieComingNew(ctx context.Context, in *MovieComingNewReq, out *MovieComingNewRep) error {
	return h.FilmServiceExtHandler.MovieComingNew(ctx, in, out)
}

func (h *FilmServiceExt) Search(ctx context.Context, in *SearchReq, out *SearchRep) error {
	return h.FilmServiceExtHandler.Search(ctx, in, out)
}

func init() { proto.RegisterFile("film.ext.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 1464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdd, 0x6e, 0x1b, 0xb7,
	0x12, 0x8e, 0x7e, 0x2c, 0x69, 0x47, 0xb1, 0xec, 0x30, 0x76, 0xce, 0x46, 0xc7, 0x31, 0x7c, 0x16,
	0xa7, 0xa8, 0xd1, 0x02, 0x42, 0xe1, 0xf4, 0x07, 0x2d, 0x50, 0xa0, 0x8e, 0xed, 0x24, 0x2a, 0x62,
	0x23, 0x58, 0xa5, 0x48, 0x7b, 0xb9, 0x5e, 0x31, 0x32, 0xdb, 0xfd, 0x33, 0x97, 0xb2, 0xa3, 0x27,
	0xe8, 0xf3, 0xf4, 0xa6, 0x05, 0x0a, 0xf4, 0x29, 0xfa, 0x42, 0xc5, 0x0c, 0xc9, 0xd5, 0xae, 0xb5,
	0x2a, 0x72, 0x25, 0xce, 0xc7, 0xe1, 0x2c, 0x39, 0xfc, 0xe6, 0xe3, 0x08, 0x06, 0xef, 0x44, 0x14,
	0x8f, 0xf8, 0x7b, 0x35, 0xca, 0x64, 0xaa, 0x52, 0xd6, 0xcc, 0x2e, 0xbd, 0x11, 0x6c, 0xbf, 0x4c,
	0xd5, 0xeb, 0x28, 0x58, 0x9c, 0xa7, 0x37, 0x82, 0xe7, 0x3e, 0xbf, 0x66, 0x43, 0xe8, 0x45, 0x69,
	0x18, 0x28, 0x91, 0x26, 0x6e, 0xe3, 0xa0, 0x71, 0xd8, 0xf2, 0x0b, 0xdb, 0xfb, 0x62, 0xc5, 0x3f,
	0x63, 0xff, 0x83, 0x4e, 0x4c, 0x86, 0xdb, 0x38, 0x68, 0x1d, 0xf6, 0x8f, 0x9c, 0x51, 0x76, 0x39,
	0xa2, 0x69, 0xdf, 0x4c, 0x78, 0x7f, 0x37, 0x60, 0x83, 0x10, 0xb6, 0x0d, 0x2d, 0x11, 0xcf, 0x28,
	0xae, 0xe3, 0xe3, 0x90, 0xb9, 0xd0, 0x25, 0xaf, 0xf1, 0xd4, 0x6d, 0xd2, 0xd7, 0xac, 0x89, 0x33,
	0x4a, 0xa8, 0x88, 0x9f, 0x24, 0x6e, 0x8b, 0xfc, 0xad, 0xc9, 0x3e, 0x81, 0x6d, 0x72, 0x9a, 0xcc,
	0xb3, 0x2c, 0x95, 0xea, 0xcd, 0x22, 0xe3, 0x6e, 0x9b, 0x5c, 0x56, 0x70, 0xe6, 0xc1, 0x7d, 0x3c,
	0xf8, 0xa9, 0x90, 0x3c, 0x54, 0xa9, 0x74, 0x37, 0xc8, 0xaf, 0x82, 0xb1, 0x47, 0xd0, 0x09, 0x70,
	0x90, 0xbb, 0x9d, 0x83, 0xd6, 0xa1, 0xe3, 0x1b, 0x8b, 0xed, 0x81, 0x43, 0x7e, 0x32, 0x88, 0x03,
	0xb7, 0x4b, 0x0b, 0x97, 0x80, 0xf7, 0x67, 0x1b, 0x7a, 0x2f, 0x53, 0xa5, 0x0f, 0xb6, 0x07, 0x0e,
	0x2d, 0xba, 0x08, 0x62, 0x4e, 0x89, 0x70, 0xfc, 0x25, 0xc0, 0xfe, 0x0f, 0x9b, 0x61, 0x1a, 0xc7,
	0x69, 0x32, 0xc9, 0x78, 0x28, 0x82, 0x88, 0x8e, 0xea, 0xf8, 0x55, 0x10, 0xb7, 0x3a, 0x35, 0x5b,
	0xa2, 0x30, 0xfa, 0xd4, 0x15, 0xcc, 0x26, 0xb0, 0xbd, 0x4c, 0x20, 0x83, 0xb6, 0xc8, 0x9f, 0x9e,
	0xd2, 0xc1, 0x5a, 0x3e, 0x8d, 0xf1, 0x40, 0x22, 0x3f, 0x3d, 0x3f, 0xfe, 0xd1, 0xed, 0x10, 0x6a,
	0x2c, 0xbc, 0x5b, 0x91, 0x3f, 0x17, 0x91, 0xe2, 0x92, 0xce, 0xd3, 0xf2, 0x0b, 0x9b, 0xed, 0xc0,
	0x86, 0xc8, 0x5f, 0xa6, 0xca, 0xed, 0xd1, 0x84, 0x36, 0x74, 0xa4, 0x31, 0x46, 0x72, 0x6c, 0xa4,
	0x71, 0x11, 0x09, 0x47, 0x4f, 0x4f, 0x5d, 0xb0, 0x91, 0xb4, 0xad, 0x23, 0x5d, 0xf0, 0x5b, 0xb7,
	0x6f, 0x23, 0x5d, 0xf0, 0x5b, 0x8c, 0x14, 0xf1, 0x64, 0xa6, 0xae, 0xdc, 0xfb, 0x3a, 0x92, 0xb6,
	0xca, 0x04, 0xd8, 0xac, 0x12, 0x80, 0x41, 0x5b, 0x9e, 0x06, 0x0b, 0x77, 0xa0, 0x4f, 0x86, 0x63,
	0x8c, 0x22, 0xcf, 0xd3, 0x44, 0x5d, 0xb9, 0x5b, 0x3a, 0x8a, 0xb6, 0xf0, 0x9b, 0xf2, 0x27, 0x1e,
	0x48, 0x77, 0x5b, 0x7f, 0x93, 0x0c, 0x76, 0x00, 0x7d, 0x19, 0x28, 0x91, 0xcc, 0x9e, 0x8b, 0x24,
	0x88, 0xdc, 0x07, 0x07, 0x8d, 0xc3, 0xa6, 0x5f, 0x86, 0xd8, 0x7d, 0x68, 0x28, 0x97, 0x51, 0x36,
	0x1b, 0xaa, 0x4c, 0xb9, 0x87, 0x55, 0xca, 0xd9, 0x99, 0xb3, 0xc4, 0xdd, 0x29, 0xcd, 0x9c, 0x25,
	0xb8, 0x4b, 0x85, 0x04, 0xdc, 0x25, 0x98, 0xc6, 0xf8, 0xdd, 0xdb, 0x20, 0x51, 0x7c, 0x7a, 0x92,
	0xce, 0x13, 0xe5, 0x3e, 0xa2, 0x3d, 0x95, 0x21, 0xef, 0xf7, 0x2e, 0x0c, 0x9e, 0x8b, 0x28, 0x3e,
	0x8e, 0xa2, 0x73, 0x9e, 0xe7, 0xc1, 0x8c, 0x63, 0xa0, 0x28, 0x9d, 0xa5, 0xa6, 0x38, 0x68, 0x8c,
	0x69, 0x46, 0xc2, 0xbd, 0x4a, 0x93, 0x99, 0x29, 0x8f, 0xc2, 0x46, 0xba, 0x88, 0x7c, 0xc2, 0x23,
	0x1e, 0xaa, 0x09, 0x0f, 0x14, 0xd1, 0xa5, 0xe5, 0x57, 0x30, 0xcb, 0xe0, 0xd7, 0x52, 0x84, 0xba,
	0x44, 0x9a, 0xfe, 0x12, 0xc0, 0x3a, 0x42, 0x63, 0x12, 0x4a, 0xce, 0x93, 0x5b, 0x29, 0x90, 0x16,
	0xba, 0x3e, 0x56, 0x70, 0xb6, 0x0f, 0x80, 0x6c, 0xe5, 0x89, 0xba, 0x98, 0xc7, 0x86, 0x56, 0x25,
	0xc4, 0xee, 0x94, 0x88, 0xab, 0x4b, 0xa5, 0xb0, 0xd9, 0x11, 0xec, 0x88, 0xdc, 0x14, 0xe5, 0x38,
	0x89, 0x44, 0xc2, 0xdf, 0x06, 0x2a, 0xbc, 0x32, 0x4c, 0xab, 0x9d, 0xc3, 0x78, 0xa1, 0xe4, 0x81,
	0xe2, 0xc7, 0x8a, 0xa8, 0xe7, 0xf8, 0x85, 0x8d, 0x97, 0x71, 0x29, 0x66, 0x54, 0xf6, 0x9a, 0x7b,
	0xd6, 0xac, 0x56, 0x6c, 0xff, 0x4e, 0xc5, 0xb2, 0x43, 0xd8, 0x9a, 0xe7, 0x5c, 0x1e, 0x87, 0x21,
	0xcf, 0xf3, 0x37, 0x22, 0xe6, 0xb9, 0xe1, 0xe2, 0x5d, 0x18, 0x0b, 0x16, 0x97, 0x3d, 0x4b, 0xdf,
	0xa7, 0xef, 0xde, 0x61, 0xee, 0x36, 0x29, 0x77, 0x55, 0x70, 0x45, 0x5b, 0x06, 0x35, 0xda, 0x32,
	0x02, 0x86, 0xc1, 0x5f, 0x89, 0x5f, 0xf4, 0xc1, 0xf4, 0x67, 0x35, 0x79, 0x6b, 0x66, 0xf0, 0x4e,
	0x10, 0x3d, 0xd1, 0x99, 0xd5, 0xde, 0x9a, 0xd3, 0x2b, 0xb8, 0x91, 0x95, 0x2c, 0x48, 0x16, 0xe3,
	0x3c, 0x9f, 0xf3, 0x29, 0x11, 0x5c, 0xcb, 0xca, 0x12, 0xc4, 0x6c, 0x85, 0xc8, 0x39, 0xb9, 0x30,
	0x44, 0xb7, 0x26, 0xee, 0xdf, 0xdc, 0xe0, 0x24, 0x4c, 0x25, 0x27, 0xce, 0x37, 0xfd, 0x0a, 0x56,
	0xc8, 0xcb, 0x4e, 0xad, 0xbc, 0xec, 0xae, 0x95, 0x97, 0x47, 0xeb, 0xe4, 0xe5, 0x3f, 0xf5, 0xf2,
	0xe2, 0xae, 0x95, 0x97, 0xc7, 0xeb, 0xe4, 0x65, 0x58, 0x96, 0x17, 0x2b, 0x16, 0xff, 0xad, 0x15,
	0x8b, 0xbd, 0x7a, 0xb1, 0x78, 0x52, 0x16, 0x8b, 0x15, 0x91, 0xde, 0xaf, 0x11, 0x69, 0xef, 0x7b,
	0x18, 0x90, 0xe2, 0x9f, 0x72, 0x15, 0x88, 0x08, 0x1f, 0xcc, 0x7d, 0x00, 0xfb, 0x40, 0x8e, 0xa7,
	0xe6, 0xc9, 0x2c, 0x21, 0xeb, 0x5f, 0x38, 0xef, 0x8f, 0xe6, 0x9d, 0x60, 0x19, 0x1d, 0x2e, 0x0e,
	0x66, 0xdc, 0xa8, 0x80, 0x36, 0xca, 0xba, 0xd4, 0x5c, 0xab, 0x4b, 0xad, 0xaa, 0x2e, 0xe1, 0xe1,
	0x49, 0xe8, 0x4c, 0xdd, 0x1b, 0x0b, 0x13, 0xb5, 0xc0, 0xb3, 0x9b, 0xf7, 0x02, 0xc7, 0x9a, 0x22,
	0x89, 0xe2, 0x89, 0xa2, 0xca, 0x26, 0x8a, 0x90, 0x59, 0xa8, 0x5b, 0x97, 0x9e, 0x34, 0xad, 0x6e,
	0x2e, 0x74, 0xe5, 0x3c, 0x41, 0x0a, 0x9a, 0x0a, 0xb6, 0xe6, 0x6a, 0x0a, 0x9d, 0xba, 0x77, 0x6e,
	0x08, 0x3d, 0xfb, 0xa6, 0x51, 0xfd, 0x3a, 0x7e, 0x61, 0xb3, 0x8f, 0xa0, 0x2b, 0x79, 0xc4, 0x83,
	0x9c, 0x53, 0xf9, 0xf6, 0x8f, 0xfa, 0xd8, 0x4e, 0xf8, 0x1a, 0xf2, 0xed, 0x9c, 0xf7, 0x35, 0x74,
	0x0d, 0xb6, 0xd2, 0xaf, 0x38, 0xcb, 0x7e, 0x05, 0x77, 0x3f, 0x0d, 0x14, 0x37, 0x49, 0xa3, 0xb1,
	0xf7, 0x39, 0xb8, 0x94, 0xf3, 0x13, 0xc9, 0xa7, 0x42, 0xe5, 0x6f, 0x85, 0xba, 0x42, 0xe9, 0xa0,
	0xde, 0xc7, 0x85, 0xee, 0xb9, 0xb9, 0x2a, 0x7d, 0x8f, 0xd6, 0xf4, 0xbe, 0x59, 0xbb, 0x2a, 0x63,
	0xfb, 0xb0, 0x81, 0x79, 0xb1, 0x0d, 0x50, 0x0f, 0x77, 0x8c, 0x93, 0xbe, 0x86, 0x3d, 0x01, 0x6d,
	0x12, 0xa7, 0x21, 0xf4, 0x10, 0x30, 0x2d, 0x02, 0xed, 0xd4, 0xda, 0x48, 0x22, 0x3b, 0x3e, 0x0b,
	0xcd, 0x7e, 0x4b, 0x08, 0xe6, 0x25, 0xe3, 0x32, 0x4f, 0x93, 0xdc, 0x6d, 0xd1, 0x57, 0x28, 0x2f,
	0xaf, 0x35, 0xe4, 0xdb, 0x39, 0xef, 0xd7, 0x06, 0x74, 0x0d, 0xb8, 0x86, 0x4a, 0x0c, 0xda, 0x09,
	0x6e, 0xc0, 0xa4, 0x04, 0xc7, 0x48, 0x15, 0xfc, 0x2d, 0x38, 0x64, 0x2c, 0x54, 0x53, 0x99, 0x46,
	0xfc, 0x24, 0xbd, 0xe1, 0xd2, 0xb4, 0x1c, 0x4b, 0x00, 0x67, 0xf5, 0x67, 0x31, 0xc3, 0xfa, 0xd9,
	0x58, 0x02, 0xde, 0xc7, 0xd0, 0x1f, 0xe3, 0x07, 0x8f, 0xa3, 0xc8, 0x64, 0x76, 0x4d, 0x11, 0x7c,
	0x56, 0x76, 0xa4, 0x76, 0x92, 0x36, 0x5a, 0x69, 0x27, 0xc9, 0xc1, 0x37, 0x13, 0xde, 0x13, 0xd8,
	0x20, 0xa0, 0xfe, 0x84, 0xde, 0x43, 0x78, 0xf0, 0xca, 0x10, 0xa0, 0xe8, 0x6a, 0xbd, 0x2f, 0x57,
	0xc1, 0x0f, 0x6a, 0x5d, 0x1f, 0xc2, 0x03, 0x7d, 0xef, 0x69, 0x2c, 0x92, 0xd9, 0x05, 0xbf, 0x35,
	0xc1, 0xee, 0x82, 0x1f, 0x14, 0xec, 0x02, 0x9c, 0x09, 0x0f, 0x64, 0x78, 0x85, 0xfe, 0x9f, 0x42,
	0x2f, 0x9f, 0x5f, 0xfe, 0xcc, 0x43, 0x65, 0x57, 0x6c, 0xe1, 0x0a, 0xed, 0xa0, 0xd7, 0x15, 0x0e,
	0x78, 0x52, 0x95, 0x2a, 0xd3, 0x38, 0xb6, 0x7c, 0x6d, 0x78, 0x8f, 0x97, 0xf1, 0xae, 0xb1, 0x93,
	0xb9, 0x36, 0x89, 0x68, 0x5c, 0x7b, 0xbf, 0x35, 0xa0, 0x5f, 0x0a, 0x45, 0x01, 0x50, 0x18, 0x6c,
	0xaa, 0xc8, 0x60, 0x03, 0x68, 0x8a, 0xa9, 0xa1, 0x42, 0x53, 0x4c, 0xd9, 0x81, 0x4d, 0x68, 0x8b,
	0x6a, 0x0f, 0x8a, 0xdc, 0xe7, 0x96, 0x3e, 0x1e, 0x74, 0x66, 0x3c, 0x91, 0x3c, 0x77, 0xdb, 0xb4,
	0x67, 0x72, 0x79, 0x41, 0x88, 0x6f, 0x66, 0x2a, 0x0a, 0xe3, 0x18, 0x85, 0xf1, 0x0a, 0x35, 0xea,
	0x2c, 0x43, 0xfb, 0x84, 0x58, 0x65, 0xf2, 0xf6, 0xa0, 0xf3, 0xa2, 0x88, 0x40, 0xaa, 0xd3, 0x58,
	0xf6, 0x54, 0x9e, 0x07, 0x1d, 0xed, 0x8f, 0x5c, 0x0a, 0x6e, 0xb8, 0xb4, 0x17, 0xdf, 0xf4, 0xad,
	0xe9, 0xed, 0x43, 0x47, 0x6f, 0x17, 0xcf, 0x9b, 0xc7, 0x41, 0x14, 0xd9, 0xf3, 0x92, 0x81, 0xff,
	0x77, 0x5e, 0x70, 0x85, 0x7d, 0x57, 0xfe, 0x6c, 0x71, 0x22, 0xa6, 0xe6, 0xff, 0x4e, 0x28, 0x12,
	0x1e, 0x07, 0x45, 0xd1, 0x17, 0x36, 0xfe, 0xdf, 0xa9, 0xfa, 0xe7, 0x1f, 0x72, 0xcf, 0x47, 0x7f,
	0xb5, 0x74, 0x73, 0x37, 0xe1, 0xf2, 0x46, 0x84, 0xfc, 0xec, 0xbd, 0x62, 0xdf, 0xc2, 0x66, 0xe5,
	0x9f, 0x13, 0xdb, 0xc1, 0x65, 0x77, 0xff, 0x7c, 0x0d, 0xeb, 0xd0, 0xcc, 0xbb, 0xc7, 0xbe, 0x82,
	0x7e, 0xe9, 0xa1, 0x60, 0xac, 0xf8, 0x66, 0xf1, 0x0c, 0x0d, 0x57, 0x31, 0x5c, 0xf8, 0x03, 0xec,
	0xd6, 0xea, 0x16, 0xdb, 0x2b, 0xdc, 0x6b, 0x84, 0x70, 0xf8, 0x6f, 0xb3, 0x18, 0x76, 0x04, 0x3d,
	0x5b, 0xb4, 0x6c, 0xab, 0x60, 0x89, 0xae, 0xf5, 0xe1, 0x1d, 0x00, 0xfd, 0xbf, 0x83, 0x41, 0xb5,
	0xfc, 0xd8, 0x2e, 0x3a, 0xad, 0xd4, 0xe9, 0xb0, 0x16, 0x36, 0x11, 0xaa, 0x35, 0xa7, 0x23, 0xac,
	0x14, 0xe7, 0xb0, 0x16, 0xc6, 0x08, 0x87, 0xd0, 0xd1, 0x15, 0xc1, 0x36, 0x97, 0x85, 0x86, 0x2b,
	0x2a, 0x66, 0xe6, 0xdd, 0xbb, 0xec, 0xd0, 0x3f, 0xe4, 0xa7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x82, 0xb4, 0x93, 0x16, 0x33, 0x0f, 0x00, 0x00,
}
