// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.ext.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RegistAccountReq struct {
	UserName string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RegistAccountReq) Reset()                    { *m = RegistAccountReq{} }
func (m *RegistAccountReq) String() string            { return proto.CompactTextString(m) }
func (*RegistAccountReq) ProtoMessage()               {}
func (*RegistAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *RegistAccountReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegistAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegistAccountRsp struct {
}

func (m *RegistAccountRsp) Reset()                    { *m = RegistAccountRsp{} }
func (m *RegistAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*RegistAccountRsp) ProtoMessage()               {}
func (*RegistAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type LoginAccountReq struct {
}

func (m *LoginAccountReq) Reset()                    { *m = LoginAccountReq{} }
func (m *LoginAccountReq) String() string            { return proto.CompactTextString(m) }
func (*LoginAccountReq) ProtoMessage()               {}
func (*LoginAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type LoginAccountRsp struct {
}

func (m *LoginAccountRsp) Reset()                    { *m = LoginAccountRsp{} }
func (m *LoginAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginAccountRsp) ProtoMessage()               {}
func (*LoginAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type ResetAccountReq struct {
}

func (m *ResetAccountReq) Reset()                    { *m = ResetAccountReq{} }
func (m *ResetAccountReq) String() string            { return proto.CompactTextString(m) }
func (*ResetAccountReq) ProtoMessage()               {}
func (*ResetAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

type ResetAccountRsp struct {
}

func (m *ResetAccountRsp) Reset()                    { *m = ResetAccountRsp{} }
func (m *ResetAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*ResetAccountRsp) ProtoMessage()               {}
func (*ResetAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func init() {
	proto.RegisterType((*RegistAccountReq)(nil), "pb.RegistAccountReq")
	proto.RegisterType((*RegistAccountRsp)(nil), "pb.RegistAccountRsp")
	proto.RegisterType((*LoginAccountReq)(nil), "pb.LoginAccountReq")
	proto.RegisterType((*LoginAccountRsp)(nil), "pb.LoginAccountRsp")
	proto.RegisterType((*ResetAccountReq)(nil), "pb.ResetAccountReq")
	proto.RegisterType((*ResetAccountRsp)(nil), "pb.ResetAccountRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserServiceExt service

type UserServiceExtClient interface {
	// 注册用户
	RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error)
	// 用户登录
	LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error)
	// 密码重置
	ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error)
}

type userServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceExtClient(serviceName string, c client.Client) UserServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &userServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceExtClient) RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.RegistAccount", in)
	out := new(RegistAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.LoginAccount", in)
	out := new(LoginAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.ResetAccount", in)
	out := new(ResetAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServiceExt service

type UserServiceExtHandler interface {
	// 注册用户
	RegistAccount(context.Context, *RegistAccountReq, *RegistAccountRsp) error
	// 用户登录
	LoginAccount(context.Context, *LoginAccountReq, *LoginAccountRsp) error
	// 密码重置
	ResetAccount(context.Context, *ResetAccountReq, *ResetAccountRsp) error
}

func RegisterUserServiceExtHandler(s server.Server, hdlr UserServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserServiceExt{hdlr}, opts...))
}

type UserServiceExt struct {
	UserServiceExtHandler
}

func (h *UserServiceExt) RegistAccount(ctx context.Context, in *RegistAccountReq, out *RegistAccountRsp) error {
	return h.UserServiceExtHandler.RegistAccount(ctx, in, out)
}

func (h *UserServiceExt) LoginAccount(ctx context.Context, in *LoginAccountReq, out *LoginAccountRsp) error {
	return h.UserServiceExtHandler.LoginAccount(ctx, in, out)
}

func (h *UserServiceExt) ResetAccount(ctx context.Context, in *ResetAccountReq, out *ResetAccountRsp) error {
	return h.UserServiceExtHandler.ResetAccount(ctx, in, out)
}

func init() { proto.RegisterFile("user.ext.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2d, 0x4e, 0x2d,
	0xd2, 0x4b, 0xad, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xf2,
	0xe2, 0x12, 0x08, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x71, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x09,
	0x4a, 0x2d, 0x14, 0x92, 0xe2, 0xe2, 0x00, 0xa9, 0xf4, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12,
	0x4c, 0x10, 0x39, 0x18, 0x5f, 0x49, 0x08, 0xdd, 0xac, 0xe2, 0x02, 0x25, 0x41, 0x2e, 0x7e, 0x9f,
	0xfc, 0xf4, 0xcc, 0x3c, 0x84, 0xf1, 0x18, 0x42, 0x10, 0x55, 0x41, 0xa9, 0xc5, 0xa9, 0x25, 0xa8,
	0xaa, 0x50, 0x84, 0x8a, 0x0b, 0x8c, 0x8e, 0x33, 0x72, 0xf1, 0x85, 0x16, 0xa7, 0x16, 0x05, 0xa7,
	0x16, 0x95, 0x65, 0x26, 0xa7, 0xba, 0x56, 0x94, 0x08, 0xd9, 0x72, 0xf1, 0xa2, 0x58, 0x29, 0x24,
	0xa2, 0x57, 0x90, 0xa4, 0x87, 0xee, 0x23, 0x29, 0x2c, 0xa2, 0xc5, 0x05, 0x4a, 0x0c, 0x42, 0x56,
	0x5c, 0x3c, 0xc8, 0x4e, 0x11, 0x12, 0x06, 0xa9, 0x43, 0x73, 0xaf, 0x14, 0xa6, 0x20, 0x4c, 0x2f,
	0xb2, 0x03, 0x21, 0x7a, 0xd1, 0x7c, 0x21, 0x85, 0x29, 0x08, 0xd2, 0x9b, 0xc4, 0x06, 0x8e, 0x00,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x34, 0x63, 0x3f, 0x92, 0x01, 0x00, 0x00,
}
