// Code generated by protoc-gen-go.
// source: user.ext.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RegistAccountReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *RegistAccountReq) Reset()                    { *m = RegistAccountReq{} }
func (m *RegistAccountReq) String() string            { return proto.CompactTextString(m) }
func (*RegistAccountReq) ProtoMessage()               {}
func (*RegistAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *RegistAccountReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegistAccountReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegistAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegistAccountRsp struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *RegistAccountRsp) Reset()                    { *m = RegistAccountRsp{} }
func (m *RegistAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*RegistAccountRsp) ProtoMessage()               {}
func (*RegistAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *RegistAccountRsp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type LoginAccountReq struct {
	UserName string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginAccountReq) Reset()                    { *m = LoginAccountReq{} }
func (m *LoginAccountReq) String() string            { return proto.CompactTextString(m) }
func (*LoginAccountReq) ProtoMessage()               {}
func (*LoginAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *LoginAccountReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAccountRsp struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *LoginAccountRsp) Reset()                    { *m = LoginAccountRsp{} }
func (m *LoginAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginAccountRsp) ProtoMessage()               {}
func (*LoginAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *LoginAccountRsp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ResetAccountReq struct {
}

func (m *ResetAccountReq) Reset()                    { *m = ResetAccountReq{} }
func (m *ResetAccountReq) String() string            { return proto.CompactTextString(m) }
func (*ResetAccountReq) ProtoMessage()               {}
func (*ResetAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

type ResetAccountRsp struct {
}

func (m *ResetAccountRsp) Reset()                    { *m = ResetAccountRsp{} }
func (m *ResetAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*ResetAccountRsp) ProtoMessage()               {}
func (*ResetAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func init() {
	proto.RegisterType((*RegistAccountReq)(nil), "pb.RegistAccountReq")
	proto.RegisterType((*RegistAccountRsp)(nil), "pb.RegistAccountRsp")
	proto.RegisterType((*LoginAccountReq)(nil), "pb.LoginAccountReq")
	proto.RegisterType((*LoginAccountRsp)(nil), "pb.LoginAccountRsp")
	proto.RegisterType((*ResetAccountReq)(nil), "pb.ResetAccountReq")
	proto.RegisterType((*ResetAccountRsp)(nil), "pb.ResetAccountRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserServiceExt service

type UserServiceExtClient interface {
	// 注册用户
	RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error)
	// 用户登录
	LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error)
	// 密码重置
	ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error)
}

type userServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceExtClient(serviceName string, c client.Client) UserServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &userServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceExtClient) RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.RegistAccount", in)
	out := new(RegistAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.LoginAccount", in)
	out := new(LoginAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.ResetAccount", in)
	out := new(ResetAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServiceExt service

type UserServiceExtHandler interface {
	// 注册用户
	RegistAccount(context.Context, *RegistAccountReq, *RegistAccountRsp) error
	// 用户登录
	LoginAccount(context.Context, *LoginAccountReq, *LoginAccountRsp) error
	// 密码重置
	ResetAccount(context.Context, *ResetAccountReq, *ResetAccountRsp) error
}

func RegisterUserServiceExtHandler(s server.Server, hdlr UserServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserServiceExt{hdlr}, opts...))
}

type UserServiceExt struct {
	UserServiceExtHandler
}

func (h *UserServiceExt) RegistAccount(ctx context.Context, in *RegistAccountReq, out *RegistAccountRsp) error {
	return h.UserServiceExtHandler.RegistAccount(ctx, in, out)
}

func (h *UserServiceExt) LoginAccount(ctx context.Context, in *LoginAccountReq, out *LoginAccountRsp) error {
	return h.UserServiceExtHandler.LoginAccount(ctx, in, out)
}

func (h *UserServiceExt) ResetAccount(ctx context.Context, in *ResetAccountReq, out *ResetAccountRsp) error {
	return h.UserServiceExtHandler.ResetAccount(ctx, in, out)
}

func init() { proto.RegisterFile("user.ext.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x10, 0x15, 0x1c, 0xd0, 0x96, 0xa3, 0x43, 0xe4, 0x09, 0x79, 0x62, 0xca, 0x50,
	0x04, 0x03, 0x12, 0x03, 0x03, 0x03, 0x12, 0x62, 0x70, 0xc5, 0x4e, 0x12, 0x4e, 0x55, 0x24, 0x5a,
	0x1b, 0x9f, 0x03, 0xfd, 0x87, 0xfc, 0x2d, 0xe4, 0x84, 0x80, 0x71, 0x10, 0x62, 0xbc, 0xf7, 0x7c,
	0x77, 0xdf, 0x3d, 0x19, 0xc6, 0x0d, 0x93, 0xcd, 0x69, 0xe3, 0x72, 0x63, 0xb5, 0xd3, 0x98, 0x9a,
	0x52, 0x4c, 0xd9, 0x15, 0xae, 0xe1, 0x6f, 0x55, 0x3e, 0xc2, 0x54, 0xd1, 0xb2, 0x66, 0x77, 0x5d,
	0x55, 0xba, 0x59, 0x3b, 0x45, 0x2f, 0x38, 0x83, 0x1d, 0x5a, 0x15, 0xf5, 0x73, 0x96, 0x9c, 0x24,
	0xa7, 0x7b, 0xaa, 0x2b, 0x50, 0xc0, 0xae, 0x9f, 0x78, 0x5f, 0xac, 0x28, 0x4b, 0x5b, 0xe3, 0xab,
	0xf6, 0x9e, 0x29, 0x98, 0xdf, 0xb4, 0x7d, 0xca, 0xb6, 0x3b, 0xaf, 0xaf, 0xe5, 0x45, 0xbc, 0x81,
	0x0d, 0x4a, 0x18, 0x75, 0x24, 0xed, 0x8a, 0xfd, 0x39, 0xe4, 0xa6, 0xcc, 0x17, 0xad, 0xa2, 0x3e,
	0x1d, 0x79, 0x0b, 0x93, 0x3b, 0xbd, 0xac, 0xd7, 0x01, 0x58, 0x88, 0x90, 0xfc, 0x81, 0x90, 0x46,
	0x08, 0xe7, 0xd1, 0xa8, 0x7f, 0x12, 0x1c, 0xc1, 0x44, 0x11, 0x53, 0x10, 0xcd, 0x40, 0x62, 0x33,
	0x7f, 0x4f, 0x60, 0xfc, 0xc0, 0x64, 0x17, 0x64, 0x5f, 0xeb, 0x8a, 0x6e, 0x36, 0x0e, 0xaf, 0xe0,
	0xf0, 0xc7, 0xc9, 0x38, 0xf3, 0xd3, 0xe3, 0x9c, 0xc5, 0x2f, 0x2a, 0x1b, 0xb9, 0x85, 0x97, 0x70,
	0x10, 0xe2, 0xe2, 0xb1, 0x7f, 0x17, 0x65, 0x21, 0x86, 0x62, 0xdf, 0x1b, 0x02, 0x76, 0xbd, 0xd1,
	0x15, 0x62, 0x28, 0xfa, 0xde, 0x72, 0xd4, 0x7e, 0x89, 0xb3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xeb, 0xb1, 0xae, 0xca, 0x3a, 0x02, 0x00, 0x00,
}
