// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.ext.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RegistAccountReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *RegistAccountReq) Reset()                    { *m = RegistAccountReq{} }
func (m *RegistAccountReq) String() string            { return proto.CompactTextString(m) }
func (*RegistAccountReq) ProtoMessage()               {}
func (*RegistAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *RegistAccountReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegistAccountReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegistAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegistAccountRsp struct {
}

func (m *RegistAccountRsp) Reset()                    { *m = RegistAccountRsp{} }
func (m *RegistAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*RegistAccountRsp) ProtoMessage()               {}
func (*RegistAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type LoginAccountReq struct {
	UserName string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginAccountReq) Reset()                    { *m = LoginAccountReq{} }
func (m *LoginAccountReq) String() string            { return proto.CompactTextString(m) }
func (*LoginAccountReq) ProtoMessage()               {}
func (*LoginAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *LoginAccountReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAccountRsp struct {
}

func (m *LoginAccountRsp) Reset()                    { *m = LoginAccountRsp{} }
func (m *LoginAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginAccountRsp) ProtoMessage()               {}
func (*LoginAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

type ResetAccountReq struct {
}

func (m *ResetAccountReq) Reset()                    { *m = ResetAccountReq{} }
func (m *ResetAccountReq) String() string            { return proto.CompactTextString(m) }
func (*ResetAccountReq) ProtoMessage()               {}
func (*ResetAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

type ResetAccountRsp struct {
}

func (m *ResetAccountRsp) Reset()                    { *m = ResetAccountRsp{} }
func (m *ResetAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*ResetAccountRsp) ProtoMessage()               {}
func (*ResetAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

type WantScoreReq struct {
	UserId   int64  `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	OrderNum string `protobuf:"bytes,2,opt,name=orderNum" json:"orderNum,omitempty"`
	Score    int64  `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
}

func (m *WantScoreReq) Reset()                    { *m = WantScoreReq{} }
func (m *WantScoreReq) String() string            { return proto.CompactTextString(m) }
func (*WantScoreReq) ProtoMessage()               {}
func (*WantScoreReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *WantScoreReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *WantScoreReq) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *WantScoreReq) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type WantScoreRsp struct {
}

func (m *WantScoreRsp) Reset()                    { *m = WantScoreRsp{} }
func (m *WantScoreRsp) String() string            { return proto.CompactTextString(m) }
func (*WantScoreRsp) ProtoMessage()               {}
func (*WantScoreRsp) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func init() {
	proto.RegisterType((*RegistAccountReq)(nil), "pb.RegistAccountReq")
	proto.RegisterType((*RegistAccountRsp)(nil), "pb.RegistAccountRsp")
	proto.RegisterType((*LoginAccountReq)(nil), "pb.LoginAccountReq")
	proto.RegisterType((*LoginAccountRsp)(nil), "pb.LoginAccountRsp")
	proto.RegisterType((*ResetAccountReq)(nil), "pb.ResetAccountReq")
	proto.RegisterType((*ResetAccountRsp)(nil), "pb.ResetAccountRsp")
	proto.RegisterType((*WantScoreReq)(nil), "pb.WantScoreReq")
	proto.RegisterType((*WantScoreRsp)(nil), "pb.WantScoreRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserServiceExt service

type UserServiceExtClient interface {
	// 注册用户
	RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error)
	// 用户登录
	LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error)
	// 密码重置
	ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error)
	// 评分
	WantScore(ctx context.Context, in *WantScoreReq, opts ...client.CallOption) (*WantScoreRsp, error)
}

type userServiceExtClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceExtClient(serviceName string, c client.Client) UserServiceExtClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &userServiceExtClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceExtClient) RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.RegistAccount", in)
	out := new(RegistAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) LoginAccount(ctx context.Context, in *LoginAccountReq, opts ...client.CallOption) (*LoginAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.LoginAccount", in)
	out := new(LoginAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) ResetAccount(ctx context.Context, in *ResetAccountReq, opts ...client.CallOption) (*ResetAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.ResetAccount", in)
	out := new(ResetAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) WantScore(ctx context.Context, in *WantScoreReq, opts ...client.CallOption) (*WantScoreRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserServiceExt.WantScore", in)
	out := new(WantScoreRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServiceExt service

type UserServiceExtHandler interface {
	// 注册用户
	RegistAccount(context.Context, *RegistAccountReq, *RegistAccountRsp) error
	// 用户登录
	LoginAccount(context.Context, *LoginAccountReq, *LoginAccountRsp) error
	// 密码重置
	ResetAccount(context.Context, *ResetAccountReq, *ResetAccountRsp) error
	// 评分
	WantScore(context.Context, *WantScoreReq, *WantScoreRsp) error
}

func RegisterUserServiceExtHandler(s server.Server, hdlr UserServiceExtHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserServiceExt{hdlr}, opts...))
}

type UserServiceExt struct {
	UserServiceExtHandler
}

func (h *UserServiceExt) RegistAccount(ctx context.Context, in *RegistAccountReq, out *RegistAccountRsp) error {
	return h.UserServiceExtHandler.RegistAccount(ctx, in, out)
}

func (h *UserServiceExt) LoginAccount(ctx context.Context, in *LoginAccountReq, out *LoginAccountRsp) error {
	return h.UserServiceExtHandler.LoginAccount(ctx, in, out)
}

func (h *UserServiceExt) ResetAccount(ctx context.Context, in *ResetAccountReq, out *ResetAccountRsp) error {
	return h.UserServiceExtHandler.ResetAccount(ctx, in, out)
}

func (h *UserServiceExt) WantScore(ctx context.Context, in *WantScoreReq, out *WantScoreRsp) error {
	return h.UserServiceExtHandler.WantScore(ctx, in, out)
}

func init() { proto.RegisterFile("user.ext.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x0d, 0x16, 0xbb, 0xd4, 0x58, 0xd7, 0x22, 0x21, 0x27, 0xd9, 0x93, 0xa7, 0x80, 0x7a,
	0x13, 0x3c, 0x78, 0xf0, 0x50, 0x90, 0x1e, 0xb6, 0x88, 0x1e, 0xcd, 0xc7, 0x50, 0x02, 0x26, 0xbb,
	0xee, 0x6c, 0xb4, 0xbf, 0xdd, 0x93, 0x4c, 0x62, 0xca, 0xba, 0x11, 0x8f, 0xef, 0xcd, 0xbc, 0xf7,
	0x32, 0x2f, 0xcb, 0xa2, 0x16, 0xc1, 0xa4, 0xb0, 0xb3, 0xa9, 0x36, 0xca, 0x2a, 0x3e, 0xd1, 0xb9,
	0x78, 0x65, 0x0b, 0x09, 0xdb, 0x0a, 0xed, 0x7d, 0x51, 0xa8, 0xb6, 0xb1, 0x12, 0xde, 0xf9, 0x92,
	0x1d, 0x42, 0x9d, 0x55, 0x6f, 0x71, 0x70, 0x11, 0x5c, 0xce, 0x64, 0x0f, 0x78, 0xc2, 0x8e, 0x48,
	0xbf, 0xce, 0x6a, 0x88, 0x27, 0xdd, 0x60, 0x8f, 0x69, 0xa6, 0x33, 0xc4, 0x4f, 0x65, 0xca, 0x38,
	0xec, 0x67, 0x03, 0x16, 0xdc, 0x4f, 0x40, 0x2d, 0x56, 0xec, 0xe4, 0x51, 0x6d, 0xab, 0xc6, 0x09,
	0x75, 0xed, 0x83, 0x7f, 0xec, 0x27, 0x9e, 0xfd, 0xa9, 0x67, 0x85, 0x9a, 0x28, 0x09, 0x08, 0xce,
	0x49, 0x23, 0x0a, 0xb5, 0x78, 0x61, 0xf3, 0xe7, 0xac, 0xb1, 0x9b, 0x42, 0x19, 0xa0, 0x0f, 0x38,
	0x67, 0x53, 0x0a, 0x5c, 0x95, 0x5d, 0x7c, 0x28, 0x7f, 0x10, 0x85, 0x2b, 0x53, 0x82, 0x59, 0xb7,
	0xf5, 0x10, 0x3e, 0x60, 0x6a, 0x0a, 0x49, 0xdf, 0x1d, 0x1d, 0xca, 0x1e, 0x88, 0xc8, 0x75, 0x46,
	0x7d, 0xfd, 0x15, 0xb0, 0xe8, 0x09, 0xc1, 0x6c, 0xc0, 0x7c, 0x54, 0x05, 0x3c, 0xec, 0x2c, 0xbf,
	0x63, 0xc7, 0xbf, 0x4a, 0xe1, 0xcb, 0x54, 0xe7, 0xa9, 0xff, 0x27, 0x92, 0x3f, 0x58, 0xd4, 0xe2,
	0x80, 0xdf, 0xb2, 0xb9, 0x7b, 0x34, 0x3f, 0xa3, 0x3d, 0xaf, 0xd1, 0x64, 0x4c, 0x0e, 0x5a, 0xb7,
	0x8a, 0x5e, 0xeb, 0xf5, 0x95, 0x8c, 0xc9, 0x4e, 0x7b, 0xc5, 0x66, 0xfb, 0xcb, 0xf8, 0x82, 0x76,
	0xdc, 0x0a, 0x13, 0x8f, 0x21, 0x49, 0x3e, 0xed, 0xde, 0xda, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0x30, 0x43, 0x6c, 0x7d, 0x02, 0x00, 0x00,
}
