CREATE TABLE comment
(
  comment_id INT(11) NOT NULL AUTO_INCREMENT,
  film_id INT(11) NOT NULL DEFAULT 0,
  title VARCHAR(150) NOT NULL DEFAULT '' COMMENT '标题',
  content TEXT NOT NULL DEFAULT '' COMMENT '内容',
  head_img VARCHAR(100) NOT NULL DEFAULT '',
  nick_name CHAR(50) NOT NULL DEFAULT '',
  create_at CHAR(20) NOT NULL DEFAULT '',
  up_num SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  user_id INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`comment_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
