CREATE TABLE film
(
  movie_id INT(11)  AUTO_INCREMENT COMMENT '影片编号',
  img char(255) DEFAULT '' COMMENT '影片logo',
  length int(11) DEFAULT 0 COMMENT '影片时长',
  is_select_seat  int(11)  DEFAULT 0 COMMENT '是否支持选座',
  film_price FLOAT DEFAULT 0 COMMENT '影片价格',
  film_screenwriter CHAR(255) DEFAULT '' COMMENT '影片编剧',
  film_director CHAR(255) DEFAULT '' COMMENT '影片导演',
  comment_num  int(11)  DEFAULT 0 COMMENT '评论人数',
  title_cn CHAR(100) COMMENT '影片名字',
  title_en CHAR(100) COMMENT '影片名字',
  is_support_inline_watch INT(11) DEFAULT  0 COMMENT '是否支持线上观看',
  create_at CHAR(20) DEFAULT '' COMMENT '记录创建时间',
  type CHAR(100) DEFAULT '' COMMENT '影片种类',
  film_drama TEXT DEFAULT '' COMMENT '影片简介',
  common_special CHAR(255) DEFAULT '' COMMENT '影片剧情',
  user_access_times INT(11) DEFAULT 0 COMMENT '用户访问次数',
  film_boxoffice FLOAT DEFAULT 0 COMMENT '影片票房',
  wanted_count  INT(11) DEFAULT 0 COMMENT '用户想看次数',
  user_comment_times  INT(11) DEFAULT 0 COMMENT '用户评分次数',
  company_issued  CHAR(255) DEFAULT '' COMMENT '发行公司',
  country   CHAR(50) DEFAULT '' COMMENT '发行国家',
  rating_final FLOAT DEFAULT 0 COMMENT '评分',
  is_3D INT(11) DEFAULT 0 COMMENT '是否3d',
  is_DMAX INT(11) DEFAULT 0 COMMENT '是否is_DMAX',
  is_filter INT(11) DEFAULT 0 COMMENT '是否is_filter',
  is_hot INT(11) DEFAULT 0 COMMENT '是否热播',
  is_IMAX INT(11) DEFAULT 0 COMMENT '是否is_IMAX',
  is_IMAX3D INT(11) DEFAULT 0 COMMENT '是否is_IMAX3D',
  is_new INT(11) DEFAULT 0 COMMENT '是否新片',
  is_ticking INT(11) DEFAULT 0 COMMENT '上映状态，0为已经上映，1为正在上映，2为即将上映',
  r_day  INT(11) DEFAULT 0 COMMENT '上映时间-日',
  r_month INT(11) DEFAULT 0 COMMENT '上映时间-月',
  r_year INT(11) DEFAULT 0 COMMENT '上映时间-年',
  PRIMARY KEY ( `movie_id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
